CREATE OR REPLACE PACKAGE EVALUACIONPRODUCTOS_PCK IS


	FUNCTION OBTENERNUMERODEACTA(
    P_IDEMPRESA IN NUMBER
  ) RETURN NUMBER;



  FUNCTION OBTENERNUMERODEINFORME(
    P_IDEMPRESA IN NUMBER
  ) RETURN NUMBER;



  PROCEDURE BORRARACTA(
    P_US_ID IN NUMBER,
	P_IDACTA IN NUMBER
  );

  PROCEDURE ESTADOEVALUACION(
    P_IDPROVEEDORPRODUCTO IN NUMBER
  );

  FUNCTION OBTENERESTADOINFORME(
    P_IDINFORME IN NUMBER
  )  RETURN NUMBER;


  FUNCTION permitirBorrarActa(
    P_IDACTA IN NUMBER
  )  RETURN VARCHAR2;

  FUNCTION OBTENERESTADOACTA(
    P_IDACTA IN NUMBER
  )  RETURN NUMBER;


  PROCEDURE MODIFICARACTA(
    P_US_ID IN NUMBER,
    P_IDACTA IN NUMBER,
	P_IDPROVEEDORPRODUCTO IN NUMBER,
	P_IDRESPONSABLEACTA IN NUMBER,
    P_IDNUEVORESPONSABLEEVALUACION IN NUMBER,
	P_IDINFORME IN NUMBER,
	P_NUMEROMUESTRAS IN varchar2,
	P_MUESTRASCRITERIOPROV IN VARCHAR2,
	P_ANEXOS IN VARCHAR2,
	P_CHKCONCLUSION IN VARCHAR2,
	P_COMENTARIOS IN VARCHAR2,
	P_COMENTARIOS_INFORMES IN VARCHAR2,
	P_COMENTARIOS_PROV IN VARCHAR2,
	P_CAMBIOS_INFORMES IN VARCHAR2,
	P_ACCION IN VARCHAR2
  );

 PROCEDURE MODIFICARINFORME(
    P_US_ID IN NUMBER,
	P_IDINFORME IN NUMBER,
	P_EVALUADORINFORME IN VARCHAR2,
    P_CARGOEVALUADORINFORME IN VARCHAR2,
	P_NUMEROMUESTRAS IN varchar2,
    P_FECHARECEPCION IN VARCHAR2,
    P_FECHAPREVISION IN VARCHAR2,
    P_EVALUACIONFUNCIONAL IN VARCHAR2,
    P_EVALUACIONENVOLTORIO IN VARCHAR2,
    P_COMENTARIOS IN VARCHAR2,
    P_CHKCONCLUSION IN VARCHAR2,
    P_FECHACIERRE IN VARCHAR2,
	P_FECHARECEPCIONMUESTRAS IN VARCHAR2,
    P_FICHATECNICA IN VARCHAR2,
    P_CERTIFICADO IN VARCHAR2,
	P_CAMBIOSCRITERIOS IN VARCHAR2,
	P_ACCION IN VARCHAR2
  );

  PROCEDURE LISTARESPONSABLESEVALUACION(
    P_IDEMPRESA IN NUMBER,
	P_IDUSUARIO IN NUMBER DEFAULT -1,
	p_ActivarEventoOnChange IN VARCHAR DEFAULT NULL
  );

  PROCEDURE LISTARESPONSABLESACTA(
    P_IDEMPRESA IN NUMBER,
	P_IDUSUARIO IN NUMBER DEFAULT -1,
	p_ActivarEventoOnChange IN VARCHAR DEFAULT NULL
  );

  PROCEDURE INFORMESEVALUACION(
	  P_IDACTA IN NUMBER
  );

  PROCEDURE BORRARINFORME(
	  P_US_ID			IN NUMBER,
		P_IDINFORME IN NUMBER
  );

  PROCEDURE BORRARANEXO(
	  P_IDANEXO IN NUMBER
  );


  PROCEDURE CREARANEXOSACTA(
    P_IDACTA IN NUMBER
  );

  PROCEDURE ACTUALIZARANEXOS(
    P_ANEXOS IN VARCHAR2
  );

  PROCEDURE ACTUALIZARINFORMES(
    P_CAMBIOS_INFORMES IN VARCHAR2
  );

  FUNCTION OBTENER_ETIQUETA_ESTADO(
    P_ID IN NUMBER
  ) RETURN VARCHAR2;

   PROCEDURE MODIFICARCRITERIOSGENERALES(
    P_US_ID              IN NUMBER,
    P_IDCRITERIO         IN NUMBER,
	P_DESCRIPCION        IN VARCHAR2,
    P_TIPOCRITERIO       IN VARCHAR2,
	P_ACCION             IN VARCHAR2
  );

  PROCEDURE CREARCRITERIOSACTA(
    P_US_ID              IN NUMBER,
	P_IDACTA             IN NUMBER
  );

  PROCEDURE MODIFICARCRITERIOSACTA(
    P_US_ID              IN NUMBER,
	P_IDACTA             IN NUMBER,
    P_IDCRITERIO         IN NUMBER,
	P_DESCRIPCION        IN VARCHAR2,
    P_TIPOCRITERIO       IN VARCHAR2,
    P_CAMBIOSCRITERIOS   IN VARCHAR2,
	P_ACCION             IN VARCHAR2
  );

  PROCEDURE  LISTACRITERIOSGENERALES(
	P_US_ID  IN NUMBER,
	P_TIPO   IN VARCHAR2,
	P_IDCRITERIOEXCLUIDO IN NUMBER DEFAULT -1
  );

  PROCEDURE  LISTACRITERIOSACTA(
    P_IDACTA IN NUMBER,
	P_TIPO   IN VARCHAR2,
	P_IDCRITERIOEXCLUIDO IN NUMBER DEFAULT -1,
	P_IDINFORME IN NUMBER DEFAULT -1
  );

  PROCEDURE  LISTACRITERIOSINFORME(
	P_IDINFORME IN NUMBER,
	P_TIPO   IN VARCHAR2
  );


  PROCEDURE ASIGNARCRITERIOSALACTA(
    P_CAMBIOSCRITERIOS IN VARCHAR2,
	P_IDACTA           IN NUMBER,
	P_IDCRITERIO	   IN NUMBER DEFAULT -1
  );

  PROCEDURE BORRARCRITERIOSACTAS(
    P_IDACTA IN NUMBER
  );

  PROCEDURE BORRARRESPUESTASCRITERIOS(
    P_IDCRITERIOACTA IN NUMBER
  );

  FUNCTION CRITERIOSMODIFICABLES(
    P_IDACTA IN NUMBER
  )  RETURN BOOLEAN;

  PROCEDURE GUARDARRESPUESTASCRITERIOS(
    P_IDINFORME IN NUMBER,
	P_CAMBIOSCRITERIOS IN VARCHAR2
  );

  PROCEDURE BORRARRESPUESTASINFORME(
    P_IDINFORME IN NUMBER
  );

  PROCEDURE ADJUDICARPRODUCTOS(
    P_US_ID IN NUMBER,
	P_CAMBIOSADJUDICATURAS IN VARCHAR2
  );

  PROCEDURE DESADJUDICARPROVEEDORES(
    P_US_ID IN NUMBER,
	P_CAMBIOSADJUDICATURAS IN VARCHAR2
  );

  PROCEDURE ADJUDICATURAPROVEEDOR(
    P_IDPROVEEDOR IN NUMBER
  );

  FUNCTION OBTENER_ETIQUETA_ESTADO_UNIV(
    P_IDESTADO NUMBER,
	P_IDTIPOESTADO NUMBER
  )RETURN VARCHAR2;

  FUNCTION OBTENER_IDESTADO_UNIV(
    P_IDESTADO NUMBER,
	P_IDTIPOESTADO NUMBER
  )RETURN number;


END;



/
SHOW ERRORS;


CREATE OR REPLACE PACKAGE BODY EVALUACIONPRODUCTOS_PCK AS




  FUNCTION OBTENERNUMERODEACTA(
    P_IDEMPRESA IN NUMBER
  ) RETURN NUMBER

  IS

    V_NUMACTAEVALUACION EVALUACION_ACTAS.EV_AC_NUMERO%TYPE;

  BEGIN

    SELECT NVL(MAX(EV_AC_NUMERO),0)+1
	  INTO V_NUMACTAEVALUACION
	  FROM EVALUACION_ACTAS
	 WHERE EV_AC_IDEMPRESA=P_IDEMPRESA;

    RETURN V_NUMACTAEVALUACION;

	EXCEPTION

	WHEN OTHERS THEN
		  HTP.P('<ERROR/>');
		  MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.OBTENERNUMERODEACTA ',' ',sqlcode,sqlerrm,NULL);

  END;

  /*



  */

  FUNCTION OBTENERNUMERODEINFORME(
    P_IDEMPRESA IN NUMBER
  ) RETURN NUMBER

  IS

    V_NUMACTAEVALUACION EVALUACION_INFORMES.EV_IN_NUMERO%TYPE;

  BEGIN

    SELECT NVL(MAX(EV_IN_NUMERO),0)+1
	  INTO V_NUMACTAEVALUACION
	  FROM EVALUACION_INFORMES,
	       EVALUACION_ACTAS
	 WHERE EV_AC_IDEMPRESA=P_IDEMPRESA
	   AND EV_IN_IDACTA=EV_AC_ID;

    RETURN V_NUMACTAEVALUACION;

	EXCEPTION

	WHEN OTHERS THEN
		  HTP.P('<ERROR/>');
		  MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.OBTENERNUMERODEINFORME ',' ',sqlcode,sqlerrm,NULL);

  END;




  PROCEDURE BORRARACTA(
    P_US_ID IN NUMBER,
	  P_IDACTA IN NUMBER
  ) IS

    CURSOR cINFORMES IS
	  SELECT EV_IN_ID ID
	    FROM EVALUACION_INFORMES
	   WHERE EV_IN_IDACTA=P_IDACTA;


	CURSOR cANEXOS IS
	  SELECT EV_AAC_ID ID
	    FROM EVALUACION_ANEXOSACTAS
	   WHERE EV_AAC_IDACTA=P_IDACTA;

  BEGIN


	FOR rANEXO IN cANEXOS LOOP
	  BORRARANEXO(rANEXO.ID);
	END LOOP;



	FOR rINFORME IN cINFORMES LOOP
	  BORRARINFORME(P_US_ID,rINFORME.ID);
	END LOOP;


    BORRARCRITERIOSACTAS(P_IDACTA);


	DELETE EVALUACION_ACTAS
	WHERE EV_AC_ID=P_IDACTA;

	LOGADMINISTRACION_PCK.Insertar(P_US_ID,3,'EVALUACION_ACTAS',P_IDACTA,'ELIMINAR EL ACTA');


	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.BORRARACTA ',' ',sqlcode,sqlerrm,NULL);

  END;



  /*


  */


  PROCEDURE ESTADOEVALUACION(
    P_IDPROVEEDORPRODUCTO IN NUMBER
  )
  IS

  V_EXISTE NUMBER;

  CURSOR cACTA IS
    SELECT EV_AC_ID ID,
	       NVL(EV_AC_APTO,'P') APTO
	  FROM CATPRIV_PRODUCTOSESTANDAR,
	       CATPRIV_PROVEEDORES,
	       EVALUACION_ACTAS
	 WHERE CP_PV_ID=P_IDPROVEEDORPRODUCTO
	   AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID
	   AND CP_PRO_ID=CP_PV_IDPRODUCTOESTANDAR;


  BEGIN




     /* MIRAMOS SI EXISTE EL ACTA */

    SELECT COUNT(*)
	  INTO V_EXISTE
	  FROM CATPRIV_PRODUCTOSESTANDAR,
	       CATPRIV_PROVEEDORES,
	       EVALUACION_ACTAS
	 WHERE CP_PV_ID=P_IDPROVEEDORPRODUCTO
	   AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID;

    IF V_EXISTE>0 THEN
	  HTP.P('<ACTA_EVALUACION>');
		FOR rACTA IN cACTA LOOP
		  HTP.P('<ID>'||rACTA.ID||'</ID>');
		  HTP.P('<IDPROVEEDORPRODUCTO>'||P_IDPROVEEDORPRODUCTO||'</IDPROVEEDORPRODUCTO>');
		  HTP.P('<LABEL>Ver</LABEL>');
		  --HTP.P('<ESTADO>'||OBTENER_ETIQUETA_ESTADO(obtenerestadoacta(rACTA.ID))||'</ESTADO>');
		  HTP.P('<ESTADO>'||OBTENER_ETIQUETA_ESTADO_UNIV(OBTENER_IDESTADO_UNIV(obtenerestadoacta(rACTA.ID),10),10)||'</ESTADO>');
		  HTP.P('<IDESTADO>'||obtenerestadoacta(rACTA.ID)||'</IDESTADO>');
		  HTP.P('<APTO>'||rACTA.APTO||'</APTO>');
		  HTP.P('<ACCION>MODIFICARACTA</ACCION>');
		END LOOP;
	  HTP.P('</ACTA_EVALUACION>');
	ELSE
	  HTP.P('<ACTA_EVALUACION>');
	    HTP.P('<ID>0</ID>');
		HTP.P('<IDPROVEEDORPRODUCTO>'||P_IDPROVEEDORPRODUCTO||'</IDPROVEEDORPRODUCTO>');
		HTP.P('<LABEL>Iniciar</LABEL>');
		HTP.P('<ESTADO>No Iniciado</ESTADO>');
		HTP.P('<ACCION>NUEVOACTA</ACCION>');
	  HTP.P('</ACTA_EVALUACION>');
	END  IF;


	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.ESTADOEVALUACION',' ',sqlcode,sqlerrm,NULL);


  END;


  /*

    DEVUELVE EL ESTADO DEL INFORME
	SI ESTE ES NULO DEVUELVE  10

  */

  FUNCTION OBTENERESTADOINFORME(
    P_IDINFORME IN NUMBER
  )  RETURN NUMBER
  IS

   V_ESTADO NUMBER;

  BEGIN


     SELECT EV_IN_STATUS
	   INTO V_ESTADO
	  FROM EVALUACION_INFORMES
	 WHERE EV_IN_ID=P_IDINFORME;

	 RETURN V_ESTADO;


	EXCEPTION
    WHEN OTHERS THEN

	  RETURN 10;
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.OBTENERESTADOINFORME',' ',sqlcode,sqlerrm,NULL);

  END;


  --
  -- miramos si todos los informes tiene el estado 10, si es asi podemos borrar el acta
  --
  FUNCTION permitirBorrarActa(
    P_IDACTA IN NUMBER
  )  RETURN VARCHAR2
  IS

  -- CURSOR CON LOS INFORMES DEL ACTA
  CURSOR cINFORMES(IDACTA NUMBER) IS
    SELECT * FROM EVALUACION_INFORMES
	  WHERE EV_IN_IDACTA=IDACTA;

   V_BORRAR VARCHAR2(1);

  BEGIN

    V_BORRAR:='S';

	FOR rINFORME IN cINFORMES(P_IDACTA) LOOP

	IF OBTENERESTADOINFORME(rINFORME.EV_IN_ID)>10 AND V_BORRAR='S' THEN
	  V_BORRAR:='N';
	END IF;

	END LOOP;

	RETURN V_BORRAR;


	EXCEPTION
    WHEN OTHERS THEN

	  RETURN 10;
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.permitirBorrarActa',' P_IDACTA: '||P_IDACTA,sqlcode,sqlerrm,NULL);
       RETURN 'N';
  END;



  /*

     DEVUELVE EL ESTADO DEL ACTA.
	 LO HACE A TRAVES DE RECORRECR TODOS LOS INFOEMRS
	 QUE COMPONENE EL ACTA Y DEVUELVE EL DE MENOR NUMERO.

	 SI ESTE ES NULO DEVUELVE 10


  */


  FUNCTION OBTENERESTADOACTA(
    P_IDACTA IN NUMBER
  )  RETURN NUMBER
  IS

    -- CURSOR CON TODOS LOS INFORMES DEL ACTA

	 CURSOR cINFORMES IS
       SELECT EV_IN_ID
	     FROM EVALUACION_INFORMES
		WHERE EV_IN_IDACTA=P_IDACTA;

	 V_ESTADO NUMBER;
  BEGIN

    V_ESTADO:=100;

  -- RECORREMOS TODOS LOS INFORMES Y DEVOLVEMOS EL DE MENOR PESO


    FOR rINFORME IN cINFORMES LOOP
	  IF OBTENERESTADOINFORME(rINFORME.EV_IN_ID)<V_ESTADO THEN
	    V_ESTADO:=OBTENERESTADOINFORME(rINFORME.EV_IN_ID);
	  END IF;
	END LOOP;

	V_ESTADO:=NVL(V_ESTADO,10);

	--IF V_ESTADO=20 THEN
	  -- SI EL ESTADO ES 20  (Enviado) el estado es Creado
	  --V_ESTADO:=10;
	--ELSE
	  IF V_ESTADO>40 THEN
	    -- SI EL ESTADO ES 40 o 50 (cERRADO o archivado) BUSCAMOS EL ESTADO PROPIO DEL ACTA

		SELECT EV_AC_STATUS
		  INTO V_ESTADO
		  FROM EVALUACION_ACTAS
		 WHERE EV_AC_ID=P_IDACTA;

	  END IF;
	--END IF;

	IF V_ESTADO=100 THEN
	  V_ESTADO:=10;
	END IF;

	RETURN V_ESTADO;


	EXCEPTION
    WHEN OTHERS THEN

	  RETURN -1;
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.OBTENERESTADOACTA',' ',sqlcode,sqlerrm,NULL);

  END;



  /*

     CREAR , MODIFICAR, BORRAR ACTA

  */

  PROCEDURE MODIFICARACTA(
    P_US_ID IN NUMBER,
    P_IDACTA IN NUMBER,
	P_IDPROVEEDORPRODUCTO IN NUMBER,
	P_IDRESPONSABLEACTA IN NUMBER,
    P_IDNUEVORESPONSABLEEVALUACION IN NUMBER,
	P_IDINFORME IN NUMBER,
	P_NUMEROMUESTRAS IN varchar2,
	P_MUESTRASCRITERIOPROV IN VARCHAR2,
	P_ANEXOS IN VARCHAR2,
	P_CHKCONCLUSION IN VARCHAR2,
	P_COMENTARIOS IN VARCHAR2,
	P_COMENTARIOS_INFORMES IN VARCHAR2,
	P_COMENTARIOS_PROV IN VARCHAR2,
	P_CAMBIOS_INFORMES IN VARCHAR2,
	P_ACCION IN VARCHAR2
  )

  IS

    V_IDACTA NUMBER;
	V_NUMEROACTA NUMBER;
	V_IDEMPRESA EMPRESAS.EMP_ID%TYPE;

	V_IDINFORME NUMBER;
	V_NUMEROINFORME NUMBER;

	V_CHKCONCLUSION      VARCHAR2(1);

	V_ACCION VARCHAR2(100);


	V_ESTADOACTA NUMBER;

	V_RECIBIDO VARCHAR2(1);

	V_EVALUADOR EVALUACION_INFORMES.EV_IN_EVALUADOR%TYPE;
	V_CARGOEVALUADOR EVALUACION_INFORMES.EV_IN_CARGOEVALUADOR%TYPE;

	V_FECHAPREVISTAINFORME DATE;

	V_IDRESPONSABLEINFORME EVALUACION_INFORMES.EV_IN_IDRESPONSABLE%TYPE;

	V_PLAZODEVOLUCION NUMBER;

	V_FECHAPREVISTAMUESTRAS DATE;

	v_numeromuestrasprevistas varchar2(100);

	v_status number;

	V_MUESTRASCRITERIO_PROV VARCHAR2(1);

	v_id_acta number;


	v_estado_acta number;

	v_estadoinforme number;

	V_MODIFICAREVALUADOR VARCHAR2(1);

	v_idsolicitud number;


	v_idusuariorecepcion number;
	v_idusuariocomercial number;
	v_idempresaSOLICITUD number;
	v_idproveedormuestras number;

	v_idresponsableTMP number;
	v_idempresaTMP number;





	/*  CURSOR CON EL ACTA ACTUAL  */

	  CURSOR cACTA IS
	    SELECT EV_AC_ID             		ID,
		       EV_AC_NUMERO         		NUMERO,
			   EV_AC_FECHAINICIO			FECHAINICIO,
			   ev_ac_idempresa              idempresa,
			   CP_PV_REFERENCIA     		REFERENCIAPRODUCTO,
			   CP_PV_NOMBREPRODUCTO			NOMBREPRODUCTO,
			   CP_PRO_REFERENCIA			REFERENCIAPRIVADA,
			   CP_PRO_NOMBRE				NOMBREPRIVADO,
			   CP_PRO_DESCRIPCION		    DESCRIPCIONPRIVADA,
			   CP_PRO_UDBASE				UNIDADBASICA,
			   CP_PV_IDPROVEEDOR				PROV_ID,
			   CP_PV_NOMBREPROVEEDOR			PROV_NOMBRE,
			   EV_AC_NUMEROMUESTRAS			NUMEROMUESTRAS,
			   NVL(EV_AC_MUESTRASCRITERIO_PROV,'N')  MUESTRASCRITERIO_PROV,
			   EV_AC_APTO					APTO,
			   EV_AC_FECHACIERRE			FECHACIERRE,
			   EV_AC_COMENTARIOS			COMENTARIOS,
			   ev_ac_COMENTARIOS_INFORMES   COMENTARIOS_INFORMES,
	           ev_ac_COMENTARIOS_PROV       COMENTARIOS_PROV,
			   EV_AC_IDRESPONSABLE			RESPONSABLEACTA,
			   CEN_NOMBRE					CENTRORESPONSABLE,
			   EV_AC_STATUS                 STATUS
		  FROM EVALUACION_ACTAS,
		       CATPRIV_PROVEEDORES,
			   CATPRIV_PRODUCTOSESTANDAR,
			   CENTROS,
			   USUARIOS
		 WHERE EV_AC_ID=P_IDACTA
		   AND CP_PV_ID=EV_AC_IDPROVEEDORPRODUCTO
		   AND CP_PRO_ID=CP_PV_IDPRODUCTOESTANDAR
		   AND US_ID=EV_AC_IDRESPONSABLE
		   AND CEN_ID=US_IDCENTRO;


	/*  CURSOR CON LOS ANEXOS DEL ACTA  */


	CURSOR cANEXOS IS
	  SELECT EV_AAC_ID                  ID,
	         EV_AAC_TIPOANEXO           TIPO,
	         EV_AAC_FECHASOLICITUD	    FECHASOLICITUD,
	         EV_AAC_PREVISTAENTREGA		FECHAPREVISTA,
			 EV_AAC_IDPREVISTAENTREGA	IDFECHAPREVISTA,
	         EV_AAC_FECHAENTREGA		FECHAENTREGA,
	         EV_AAC_COMENTARIOS         COMENTARIOS,
			 CP_PV_ID                   IDPROVEEDORPRODUCTO
	    FROM EVALUACION_ANEXOSACTAS,
		     EVALUACION_ACTAS,
			 CATPRIV_PROVEEDORES
	   WHERE EV_AC_ID=P_IDACTA
	     AND EV_AAC_IDACTA=EV_AC_ID
		 AND CP_PV_ID=EV_AC_IDPROVEEDORPRODUCTO
	ORDER BY EV_AAC_ID;


	-- curosr con los informes del acta
	CURSOR cINFORMESINFORMADOS(IDACTA IN NUMBER) IS
	  SELECT *
	    FROM EVALUACION_INFORMES
	   where EV_IN_IDACTA=IDACTA
	     AND EV_IN_STATUS<>50;

	   --WHERE EV_IN_STATUS=40
	     --AND EV_IN_IDACTA=IDACTA;


  BEGIN


  /*  si la accion es null suponemos que es modificar informe */


	V_ACCION:=NVL(P_ACCION,'MODIFICARACTA');



    SELECT CEN_IDEMPRESA
    INTO V_IDEMPRESA
    FROM CENTROS,
		 USUARIOS
  WHERE US_ID=P_US_ID
    AND US_IDCENTRO=CEN_ID;



	/*   PREPARAMOS LOS CHECK   */

	SELECT DECODE(P_CHKCONCLUSION,'P',NULL,P_CHKCONCLUSION)
	  INTO V_CHKCONCLUSION
      FROM DUAL;

	SELECT DECODE(P_MUESTRASCRITERIOPROV,'on','S','N')
	  INTO V_MUESTRASCRITERIO_PROV
      FROM DUAL;


	/*   */

	IF V_ACCION='NUEVOACTA' THEN

	  /*  creamos el acta con valores por defecto */


	    /*  GENERAMOS EL SIGUIENTE ID  */

	  --SELECT NVL(MAX(EV_AC_ID),0)+1
	   -- INTO V_IDACTA
	   -- FROM EVALUACION_ACTAS;


	   SELECT ACTASEVALUACION_SEQ.NEXTVAL
	     INTO V_IDACTA
	     FROM DUAL;

		 /*  GENERAMOS EL SIGUIENTE NUMERO DE ACTA PARA LA EMPRESA  */

	  V_NUMEROACTA:=OBTENERNUMERODEACTA(V_IDEMPRESA);


	  INSERT INTO EVALUACION_ACTAS(
	    EV_AC_ID,
		EV_AC_NUMERO,
		EV_AC_IDEMPRESA,
		EV_AC_IDPROVEEDORPRODUCTO,
		EV_AC_IDRESPONSABLE,
		EV_AC_FECHAINICIO,
		EV_AC_STATUS
	  )
	  VALUES(
	    V_IDACTA,
		V_NUMEROACTA,
		V_IDEMPRESA,
		P_IDPROVEEDORPRODUCTO,
		P_US_ID,
	  TO_DATE(SYSDATE),
		10  -- ESTADO CREADO
	  );

	  update catpriv_proveedores
	    set cp_pv_aptohistorico=null
	  where cp_pv_id=P_IDPROVEEDORPRODUCTO;

	  -- insertamos en el workflow

	  Workflow_Pck.Insertar(
	    p_WF_CODIGO => V_IDACTA,
		p_WF_SUBCODIGO => 0,
		p_WF_IDESTADO => 10,
		p_WF_IDTIPO => 5,
		p_WF_IDEMPRESA =>V_IDEMPRESA,
		p_WF_IDRESPONSABLE => P_us_id,
		p_WF_FECHA_ENTRADA => SYSDATE,
		p_WF_FECHA_SALIDA => NULL,
		p_MODULO => 'evaluacionproductos_pck.MODIFICARACTA()(NUEVOACTA)',
		p_EnvioEmail => FALSE
	  );

		LOGADMINISTRACION_PCK.Insertar(P_US_ID,1,'EVALUACION_ACTAS',V_IDACTA,'NUEVO ACTA');


	  /*  creamos los anexos */

	  CREARANEXOSACTA(V_IDACTA);

	  CREARCRITERIOSACTA(P_US_ID, V_IDACTA);


	ELSE
	  IF V_ACCION='MODIFICARACTA' THEN

	    HTP.P(Utilidades_PCK.CabeceraXML);
		HTP.P('<ACTA_EVALUACION>');
	    FOR rACTA IN cACTA LOOP
		  HTP.P('<FECHAACTUAL>'||Formato.FormatoFecha(SYSDATE,2)||'</FECHAACTUAL>');
		  HTP.P('<IDACTA>'||rACTA.ID||'</IDACTA>');
		  HTP.P('<NUMEROACTA>'||rACTA.NUMERO||'</NUMEROACTA>');
		  HTP.P('<FECHAINICIO>'||Formato.FormatoFecha(rACTA.FECHAINICIO,2)||'</FECHAINICIO>');
		  LISTARESPONSABLESACTA(rACTA.idempresa,rACTA.RESPONSABLEACTA);
		  LISTARESPONSABLESEVALUACION(rACTA.idempresa);
		  HTP.P('<CENTRORESPONSABLE>'||MVM.ScapeHTMLString(rACTA.CENTRORESPONSABLE)||'</CENTRORESPONSABLE>');
		  HTP.P('<PROV_ID>'||rACTA.PROV_ID||'</PROV_ID>');
		  HTP.P('<PROV_NOMBRE>'||MVM.ScapeHTMLString(rACTA.PROV_NOMBRE)||'</PROV_NOMBRE>');
		  HTP.P('<REFERENCIAPRODUCTO>'||rACTA.REFERENCIAPRODUCTO||'</REFERENCIAPRODUCTO>');
		  HTP.P('<NOMBREPRODUCTO>'||MVM.ScapeHTMLString(rACTA.NOMBREPRODUCTO)||'</NOMBREPRODUCTO>');
		  HTP.P('<REFERENCIAPRIVADA>'||rACTA.REFERENCIAPRIVADA||'</REFERENCIAPRIVADA>');
		  HTP.P('<NOMBREPRIVADO>'||MVM.ScapeHTMLString(rACTA.NOMBREPRIVADO)||'</NOMBREPRIVADO>');
		  HTP.P('<DESCRIPCIONPRIVADA>'||UTILIDADES_PCK.TEXTOHTML(rACTA.DESCRIPCIONPRIVADA)||'</DESCRIPCIONPRIVADA>');
		  HTP.P('<UNIDADBASICA>'||rACTA.UNIDADBASICA||'</UNIDADBASICA>');
          HTP.P('<NUMEROMUESTRAS>'||UTILIDADES_PCK.TEXTOHTML(rACTA.NUMEROMUESTRAS)||'</NUMEROMUESTRAS>');
		  HTP.P('<MUESTRASCRITERIO_PROV>'||rACTA.MUESTRASCRITERIO_PROV||'</MUESTRASCRITERIO_PROV>');

		  HTP.P('<BORRAR_ACTA_ACTIVO>'||PERMITIRBORRARACTA(rACTA.ID)||'</BORRAR_ACTA_ACTIVO>');

		  HTP.P('<STATUS>'||rACTA.STATUS||'</STATUS>');
		  HTP.P('<ANEXOS>');
		  FOR rANEXO IN cANEXOS LOOP
		    HTP.P('<ANEXO>');
			  HTP.P('<ID>'||rANEXO.ID||'</ID>');
		      HTP.P('<TIPO>'||rANEXO.TIPO||'</TIPO>');
			  HTP.P('<FECHASOLICITUD>'||Formato.FormatoFecha(rANEXO.FECHASOLICITUD,2)||'</FECHASOLICITUD>');
			  --HTP.P('<FECHAPREVISTA>'||Formato.FormatoFecha(rANEXO.FECHAPREVISTA,2)||'</FECHAPREVISTA>');
			  --HTP.P('<IDFECHAPREVISTA>'||rANEXO.IDFECHAPREVISTA||'</IDFECHAPREVISTA>');
			  --HTP.P('<FECHAENTREGA>'||Formato.FormatoFecha(rANEXO.FECHAENTREGA,2)||'</FECHAENTREGA>');
			  HTP.P('<COMENTARIOS>'||MVM.ScapeHTMLString(rANEXO.COMENTARIOS)||'</COMENTARIOS>');
			  HTP.P('<COMENTARIOS_HTML>'||Utilidades_pck.TEXTOHTML(rANEXO.COMENTARIOS)||'</COMENTARIOS_HTML>');

			  --IF rANEXO.TIPO='Muestras' THEN

				--SELECT NVL(CP_PV_MUESTRAS,'N')
				  --INTO V_RECIBIDO
				  --FROM CATPRIV_PROVEEDORES
				 --WHERE CP_PV_ID=rANEXO.IDPROVEEDORPRODUCTO;

			  --ELSE

			    --IF rANEXO.TIPO='Ficha Técnica' THEN

				  --SELECT NVL(CP_PV_FICHATECNICA,'N')
				    --INTO V_RECIBIDO
				    --FROM CATPRIV_PROVEEDORES
				   --WHERE CP_PV_ID=rANEXO.IDPROVEEDORPRODUCTO;

				--ELSE

				  --IF rANEXO.TIPO='Certificado CE' THEN

					--SELECT NVL(CP_PV_CERTIFICADO,'N')
				      --INTO V_RECIBIDO
				      --FROM CATPRIV_PROVEEDORES
				    -- WHERE CP_PV_ID=rANEXO.IDPROVEEDORPRODUCTO;
				  --ELSE

					--NULL;

				  --END IF;

				--END IF;

			  --END IF;

			  --HTP.P('<RECIBIDO>'||V_RECIBIDO||'</RECIBIDO>');

			HTP.P('</ANEXO>');
		  END LOOP;
		  HTP.P('</ANEXOS>');
		  HTP.P('<APTO>'||rACTA.APTO||'</APTO>');
		  HTP.P('<FECHACIERRE>'||Formato.FormatoFecha(rACTA.FECHACIERRE,2)||'</FECHACIERRE>');
		  HTP.P('<COMENTARIOS>'||MVM.ScapeHTMLString(rACTA.COMENTARIOS)||'</COMENTARIOS>');
		  HTP.P('<COMENTARIOS_HTML>'||Utilidades_pck.TEXTOHTML(rACTA.COMENTARIOS)||'</COMENTARIOS_HTML>');

		  HTP.P('<COMENTARIOS_INFORMES>'||MVM.ScapeHTMLString(rACTA.COMENTARIOS_INFORMES)||'</COMENTARIOS_INFORMES>');
		  HTP.P('<COMENTARIOS_INFORMES_HTML>'||Utilidades_pck.TEXTOHTML(rACTA.COMENTARIOS_INFORMES)||'</COMENTARIOS_INFORMES_HTML>');

		  HTP.P('<COMENTARIOS_PROV>'||MVM.ScapeHTMLString(rACTA.COMENTARIOS_PROV)||'</COMENTARIOS_PROV>');
		  HTP.P('<COMENTARIOS_PROV_HTML>'||Utilidades_pck.TEXTOHTML(rACTA.COMENTARIOS_PROV)||'</COMENTARIOS_PROV_HTML>');

		END LOOP;

        IF CRITERIOSMODIFICABLES(P_IDACTA) THEN
		  HTP.P('<EDICIONCRITERIOS/>');
		END IF;
        INFORMESEVALUACION(P_IDACTA);
		LISTACRITERIOSACTA(P_IDACTA,'F');
		LISTACRITERIOSACTA(P_IDACTA,'E');
	    HTP.P('</ACTA_EVALUACION>');

	  ELSE
		IF V_ACCION = 'BORRARACTA' THEN

		  /*  BORRAMOS EL ACTA  */


		   BORRARACTA(P_US_ID,P_IDACTA);

		   HTP.P('<Status>');
		   HTP.P('<BORRADO/>');
		   HTP.P('</Status>');

		ELSE
		  IF V_ACCION='ANYADIRRESPONSABLE' THEN


		  /*  INSERTAMOS EL NUEVO RESPONSABLE */

		    --SELECT NVL(MAX(EV_IN_ID),0)+1
			 -- INTO V_IDINFORME
			  --FROM EVALUACION_INFORMES;

			SELECT INFORMESEVALUACION_SEQ.NEXTVAL
			  INTO V_IDINFORME
			  FROM DUAL;


			V_NUMEROINFORME:=OBTENERNUMERODEINFORME(V_IDEMPRESA);





		--SELECT US_APELLIDO1||' '||US_APELLIDO2||', '||US_NOMBRE,
			   --TU_DESCRIPCION
		  --INTO V_EVALUADOR,
	           --V_CARGOEVALUADOR
		  --FROM USUARIOS,
			   --TIPOSUSUARIOS
		 --WHERE US_ID=P_IDNUEVORESPONSABLEEVALUACION
		   --AND US_IDTIPO=TU_ID;




		    INSERT INTO EVALUACION_INFORMES(
			  EV_IN_ID,
			  EV_IN_NUMERO,
			  EV_IN_IDACTA,
			  EV_IN_IDRESPONSABLE,
			  EV_IN_FECHAINICIO,
			  EV_IN_PLAZODEVOLUCION,
			  --EV_IN_EVALUADOR,
			  --EV_IN_CARGOEVALUADOR,
			  EV_IN_STATUS
			)
			VALUES(
			  V_IDINFORME,
			  V_NUMEROINFORME,
			  P_IDACTA,
			  P_IDNUEVORESPONSABLEEVALUACION,
			  TO_DATE(SYSDATE),
			  7,
			  --V_EVALUADOR,
	          --V_CARGOEVALUADOR,
			  10
			);

			-- insertamos en el workflow

	  Workflow_Pck.Insertar(
	    p_WF_CODIGO => V_IDINFORME,
		p_WF_SUBCODIGO => 0,
		p_WF_IDESTADO => 10,
		p_WF_IDTIPO => 6,
		p_WF_IDEMPRESA =>V_IDEMPRESA,
		p_WF_IDRESPONSABLE => P_IDRESPONSABLEACTA,
		p_WF_FECHA_ENTRADA => SYSDATE,
		p_WF_FECHA_SALIDA => NULL,
		p_MODULO => 'evaluacionproductos_pck.MODIFICARACTA()(NUEVORESPONSABLE; nuevo informe)',
		p_EnvioEmail => FALSE
	  );

    LOGADMINISTRACION_PCK.Insertar(P_US_ID,1,'EVALUACION_INFORMES',V_IDINFORME,'NUEVO INFORME');



			-- actualizamos el acta

			V_ESTADOACTA:=OBTENERESTADOACTA(P_IDACTA);

			UPDATE EVALUACION_ACTAS
		           SET EV_AC_IDRESPONSABLE=P_IDRESPONSABLEACTA,
				       EV_AC_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
					   EV_AC_APTO=V_CHKCONCLUSION,
					   EV_AC_COMENTARIOS=P_COMENTARIOS,
					   ev_ac_COMENTARIOS_INFORMES=p_COMENTARIOS_INFORMES,
	                   ev_ac_COMENTARIOS_PROV=p_COMENTARIOS_PROV,
					   EV_AC_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
					   EV_AC_STATUS=V_ESTADOACTA
				 WHERE EV_AC_ID=P_IDACTA;

				 -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>V_ESTADOACTA,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => P_IDRESPONSABLEACTA,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDACTA,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>5);


			-- ACTUALIZAMOS LOS ANEXOS DEL ACTA (MUESTRAS, FICHA Y CERTIFICADO)
			ACTUALIZARANEXOS(P_ANEXOS);

			-- ACTUALIZAMOS LOS COMENTARIOS DE LOS INFORMES
			-- (ESTOS COMENTARIOOS SON LOS QUE PONE EL RESPONSABLE DEL ACTA)
			ACTUALIZARINFORMES(P_CAMBIOS_INFORMES);


		  ELSE
		    IF V_ACCION='BORRARRESPONSABLE' THEN

			  -- ACTUALIZAMOS LOS ANEXOS DEL ACTA (MUESTRAS, FICHA Y CERTIFICADO)
			  ACTUALIZARANEXOS(P_ANEXOS);

			  -- ACTUALIZAMOS LOS COMENTARIOS DE LOS INFORMES
			  -- (ESTOS COMENTARIOOS SON LOS QUE PONE EL RESPONSABLE DEL ACTA)
			  ACTUALIZARINFORMES(P_CAMBIOS_INFORMES);

			  BORRARINFORME(P_US_ID,P_IDINFORME);

			  V_ESTADOACTA:=OBTENERESTADOACTA(P_IDACTA);

			  UPDATE EVALUACION_ACTAS
		           SET EV_AC_IDRESPONSABLE=P_IDRESPONSABLEACTA,
				       EV_AC_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
					   EV_AC_APTO=V_CHKCONCLUSION,
					   EV_AC_COMENTARIOS=P_COMENTARIOS,
					   ev_ac_COMENTARIOS_INFORMES=p_COMENTARIOS_INFORMES,
	                   ev_ac_COMENTARIOS_PROV=p_COMENTARIOS_PROV,
					   EV_AC_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
					   EV_AC_STATUS=V_ESTADOACTA
				 WHERE EV_AC_ID=P_IDACTA;

				 -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>V_ESTADOACTA,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => P_IDRESPONSABLEACTA,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDACTA,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>5);



			ELSE

			  -- diferenciamos la accion de GUARDARACTA,
			  -- presentamos el boton de datos guardados, o
			  -- ACTUALIZARACTA donde recargamos la pagina y dejamos al usuario seguir
			  -- trabajando

			  IF V_ACCION = 'GUARDARACTA' or V_ACCION = 'ACTUALIZARACTA' THEN

				V_ESTADOACTA:=OBTENERESTADOACTA(P_IDACTA);

				UPDATE EVALUACION_ACTAS
		           SET EV_AC_IDRESPONSABLE=P_IDRESPONSABLEACTA,
				       EV_AC_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
					   EV_AC_APTO=V_CHKCONCLUSION,
					   EV_AC_COMENTARIOS=P_COMENTARIOS,
					   ev_ac_COMENTARIOS_INFORMES=p_COMENTARIOS_INFORMES,
	                   ev_ac_COMENTARIOS_PROV=p_COMENTARIOS_PROV,
					   EV_AC_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
					   EV_AC_STATUS=V_ESTADOACTA
				 WHERE EV_AC_ID=P_IDACTA;

				 -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>V_ESTADOACTA,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => P_IDRESPONSABLEACTA,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDACTA,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>5);

				 ACTUALIZARANEXOS(P_ANEXOS);
				 ACTUALIZARINFORMES(P_CAMBIOS_INFORMES);

			  ELSE
			    IF V_ACCION = 'ENVIARINFORME' THEN

				  -- ACTUALIZAMOS LOS ANEXOS DEL ACTA (MUESTRAS, FICHA Y CERTIFICADO)
			      ACTUALIZARANEXOS(P_ANEXOS);

				   -- ACTUALIZAMOS LOS COMENTARIOS DE LOS INFORMES
			  -- (ESTOS COMENTARIOOS SON LOS QUE PONE EL RESPONSABLE DEL ACTA)
				  ACTUALIZARINFORMES(P_CAMBIOS_INFORMES);

				  -- si la fecha de prevision de cierre no se ha informado la inicializamos a 7 dias habiles

				  SELECT EV_IN_PLAZODEVOLUCION,
				         nvl(ev_in_numeromuestrasprevistas,''),
						 DECODE(TRIM(BOTH ' ' FROM EV_IN_EVALUADOR),NULL,'S','N')
				    INTO V_PLAZODEVOLUCION,
					     v_numeromuestrasprevistas,
						 V_MODIFICAREVALUADOR
					FROM EVALUACION_INFORMES
				   WHERE EV_IN_ID=P_IDINFORME;

				  V_FECHAPREVISTAINFORME:=utilidades_pck.CALCULACONDIASHABILES(SYSDATE,V_PLAZODEVOLUCION);
				  V_FECHAPREVISTAMUESTRAS:=utilidades_pck.CALCULACONDIASHABILES(SYSDATE,7);


				  IF V_MUESTRASCRITERIO_PROV='N' THEN
				    if v_numeromuestrasprevistas is null then
				      v_status:=20;
				    else
				      v_status:=15;
					END IF;
			      ELSE

					v_status:=15;

				  END IF;





				  UPDATE EVALUACION_INFORMES
				     SET EV_IN_FECHAENVIO=TO_DATE(SYSDATE),
					     EV_IN_STATUS=v_status,
						 EV_IN_FECHAPREVISIONCIERRE=TO_DATE(V_FECHAPREVISTAINFORME),
						 EV_IN_FECHAPREVISTAMUESTRAS=TO_DATE(V_FECHAPREVISTAMUESTRAS),
						 ev_in_coment_resp_acta=p_COMENTARIOS_INFORMES,
						 EV_IN_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
						 EV_IN_MODIFICAREVALUADOR=V_MODIFICAREVALUADOR
				   WHERE EV_IN_ID=P_IDINFORME;

				   select ev_in_idacta
				     into v_id_acta
				     from EVALUACION_INFORMES
					 where ev_in_id=P_IDINFORME;

				     v_estado_acta:=OBTENERESTADOACTA(v_id_acta);

				     update EVALUACION_actas
					    set ev_ac_status=v_estado_acta
						where ev_ac_id=v_id_acta;

				   SELECT EV_IN_IDRESPONSABLE
		             INTO V_IDRESPONSABLEINFORME
		             FROM EVALUACION_INFORMES
		            WHERE EV_IN_ID=P_IDINFORME;


				   -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>v_status,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => V_IDRESPONSABLEINFORME,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDINFORME,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>6);


				   V_ESTADOACTA:=OBTENERESTADOACTA(P_IDACTA);

				   UPDATE EVALUACION_ACTAS
		           SET EV_AC_IDRESPONSABLE=P_IDRESPONSABLEACTA,
				       EV_AC_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
					   EV_AC_APTO=V_CHKCONCLUSION,
					   EV_AC_COMENTARIOS=P_COMENTARIOS,
					   ev_ac_COMENTARIOS_INFORMES=p_COMENTARIOS_INFORMES,
	                   ev_ac_COMENTARIOS_PROV=p_COMENTARIOS_PROV,
					   EV_AC_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
					   EV_AC_STATUS=V_ESTADOACTA
				 WHERE EV_AC_ID=P_IDACTA;



				 -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>V_ESTADOACTA,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => P_IDRESPONSABLEACTA,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDACTA,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>5);

				   IF v_status=15 THEN

					  EVAL_SOLICITUDMUESTRAS_PCK.solicitudmuestras(
					    P_US_ID,
	                    NULL,
	                    P_IDINFORME,
						NULL,
						NULL,
	                    NULL,
	                    NULL,
						NULL,
	                    NULL,
	                    NULL,
	                    NULL,
	                    NULL,
	                    'SOLICITAR'
					  );

				    END IF;


				ELSE

				  IF V_ACCION = 'CERRARACTA' THEN



					--UPDATE EVALUACION_INFORMES
		            --   SET EV_IN_STATUS=50
			         --WHERE EV_IN_STATUS=40
					 --  AND EV_IN_IDACTA=P_IDACTA;


					 --
					 --  finaliazamos o abortamos los informes
					 --

					 FOR rINFORMEINFORMADO IN cINFORMESINFORMADOS(P_IDACTA) LOOP

					   if rINFORMEINFORMADO.ev_in_status=40 then
					     v_estadoinforme:=50;
					   else

					     v_estadoinforme:=60;

					     -- si hay solicitudes de muestras en curso,
						 -- tambien las abortamos
						 -- el estado 27 es muestras recibidas (ha finalizad el workflow de solicitudes)
					     if rINFORMEINFORMADO.ev_in_status=15 or rINFORMEINFORMADO.ev_in_status=25 then

						   select ev_sm_id,
						          ev_sm_idusuariorecepcion,
								  ev_sm_idusuariocomercial,
								  ev_sm_idempresa
						     into v_idsolicitud,
							      v_idusuariorecepcion,
								  v_idusuariocomercial,
								  v_idempresaSOLICITUD
							from eval_solicitudmuestras
						   where ev_sm_idinforme=rINFORMEINFORMADO.EV_IN_ID;


						   v_idproveedormuestras:=utilidades_pck.EmpresaDelUsuario(v_idusuariocomercial);


						   if rINFORMEINFORMADO.ev_in_status=15 then
						     v_idresponsableTMP:=v_idusuariocomercial;
							 v_idempresaTMP:=v_idproveedormuestras;
						   else
						     v_idresponsableTMP:=v_idusuariorecepcion;
							 v_idempresaTMP:=v_idempresaSOLICITUD;
						   end if;


						   update eval_solicitudmuestras
						      set ev_sm_status=v_estadoinforme
							 where ev_sm_id=v_idsolicitud;

						   -- actualizamos el workflow
				           Workflow_Pck.Actualizar (
				             p_WF_IDESTADO_SET =>v_estadoinforme,
				             p_WF_IDEMPRESA_SET =>v_idempresaTMP,
				             p_WF_IDRESPONSABLE_SET => v_idresponsableTMP,
                             p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				             p_WF_SUBCODIGO_SET => NULL,
				             p_WF_CODIGO_WHERE => v_idsolicitud,
				             p_WF_SUBCODIGO_WHERE => NULL,
				             p_WF_IDTIPO_WHERE=>8
						   );


						 end if;
					   end if;

					   UPDATE EVALUACION_INFORMES
		                 SET EV_IN_STATUS=v_estadoinforme
			           WHERE EV_IN_ID=rINFORMEINFORMADO.EV_IN_ID;


					    -- actualizamos el workflow
				        Workflow_Pck.Actualizar (
				         p_WF_IDESTADO_SET =>v_estadoinforme,
				         p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				         p_WF_IDRESPONSABLE_SET =>rINFORMEINFORMADO.EV_IN_IDRESPONSABLE,
                         p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				         p_WF_SUBCODIGO_SET => NULL,
				         p_WF_CODIGO_WHERE => rINFORMEINFORMADO.EV_IN_ID,
				         p_WF_SUBCODIGO_WHERE => NULL,
				         p_WF_IDTIPO_WHERE=>6);

					 END LOOP;


					/*

					  EL ACTA SE FINALIZA DIRECTAMENTE SIN PASAR POR EL ESTADO CERRADO

					*/

					UPDATE EVALUACION_ACTAS
		               SET EV_AC_IDRESPONSABLE=P_IDRESPONSABLEACTA,
				           EV_AC_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
					       EV_AC_APTO=V_CHKCONCLUSION,
						   EV_AC_FECHACIERRE=TO_DATE(SYSDATE),
						   EV_AC_MUESTRASCRITERIO_PROV=V_MUESTRASCRITERIO_PROV,
					       EV_AC_COMENTARIOS=P_COMENTARIOS,
						   ev_ac_COMENTARIOS_INFORMES=p_COMENTARIOS_INFORMES,
	                       ev_ac_COMENTARIOS_PROV=p_COMENTARIOS_PROV,
						   EV_AC_STATUS=50
				     WHERE EV_AC_ID=P_IDACTA;

					 -- actualizamos el workflow
				 Workflow_Pck.Actualizar (
				   p_WF_IDESTADO_SET =>50,
				   p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				   p_WF_IDRESPONSABLE_SET => P_IDRESPONSABLEACTA,
                   p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				   p_WF_SUBCODIGO_SET => NULL,
				   p_WF_CODIGO_WHERE => P_IDACTA,
				   p_WF_SUBCODIGO_WHERE => NULL,
				   p_WF_IDTIPO_WHERE=>5);

				     ACTUALIZARANEXOS(P_ANEXOS);
					 ACTUALIZARINFORMES(P_CAMBIOS_INFORMES);

				  ELSE

				    NULL;

				  END IF;

				END IF;

			  END IF;
			END IF;
		  END IF;

		END IF;
	  END IF;
	END IF;

	IF V_ACCION ='ANYADIRRESPONSABLE' OR V_ACCION='BORRARRESPONSABLE' OR V_ACCION='ENVIARINFORME' or V_ACCION='ACTUALIZARACTA' THEN
	--IF V_ACCION ='ANYADIRRESPONSABLE' OR V_ACCION='BORRARRESPONSABLE' OR V_ACCION='GUARDARACTA' OR V_ACCION='ENVIARINFORME' THEN

	  MODIFICARACTA(
	    P_US_ID,
        P_IDACTA,
	    P_IDPROVEEDORPRODUCTO,
	    P_IDRESPONSABLEACTA,
        NULL,
		NULL,
		P_NUMEROMUESTRAS,
		P_MUESTRASCRITERIOPROV,
		P_ANEXOS,
		P_CHKCONCLUSION,
		P_COMENTARIOS,
		P_COMENTARIOS_INFORMES,
	    P_COMENTARIOS_PROV,
		P_CAMBIOS_INFORMES,
	    'MODIFICARACTA'
	  );

	ELSE
      IF V_ACCION = 'NUEVOACTA' THEN

		MODIFICARACTA(
	      P_US_ID,
          V_IDACTA,
	      P_IDPROVEEDORPRODUCTO,
	      P_US_ID,
          NULL,
		  NULL,
		  P_NUMEROMUESTRAS,
		  P_MUESTRASCRITERIOPROV,
		  P_ANEXOS,
		  P_CHKCONCLUSION,
		  P_COMENTARIOS,
		  P_COMENTARIOS_INFORMES,
	      P_COMENTARIOS_PROV,
		  P_CAMBIOS_INFORMES,
	      'MODIFICARACTA'
	  );

	  ELSE

		IF V_ACCION = 'CERRARACTA' THEN
		   HTP.P('<Status>');
		   HTP.P('<CERRADO/>');
		   HTP.P('</Status>');
		ELSE

		  IF V_ACCION='GUARDARACTA' THEN

			HTP.P('<Status>');
		   HTP.P('<GUARDADO/>');
		   HTP.P('</Status>');

		  END IF;

		END IF;

	  END IF;
	END IF;

	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.MODIFICARACTA',' ',sqlcode,sqlerrm,NULL);

  END;


  /*




  */



  PROCEDURE MODIFICARINFORME(
    P_US_ID IN NUMBER,
	P_IDINFORME IN NUMBER,
	P_EVALUADORINFORME IN VARCHAR2,
    P_CARGOEVALUADORINFORME IN VARCHAR2,
	P_NUMEROMUESTRAS IN varchar2,
    P_FECHARECEPCION IN VARCHAR2,
    P_FECHAPREVISION IN VARCHAR2,
    P_EVALUACIONFUNCIONAL IN VARCHAR2,
    P_EVALUACIONENVOLTORIO IN VARCHAR2,
    P_COMENTARIOS IN VARCHAR2,
    P_CHKCONCLUSION IN VARCHAR2,
    P_FECHACIERRE IN VARCHAR2,
	P_FECHARECEPCIONMUESTRAS IN VARCHAR2,
    P_FICHATECNICA IN VARCHAR2,
    P_CERTIFICADO IN VARCHAR2,
	P_CAMBIOSCRITERIOS IN VARCHAR2,
	P_ACCION IN VARCHAR2
  )

  IS

	V_IDEMPRESA EMPRESAS.EMP_ID%TYPE;
	V_IDINFORME NUMBER;

	V_CHKCONCLUSION      VARCHAR2(1);

	V_IDRESPONSABLE   NUMBER;
	V_ESTADOINFORME   		  NUMBER;

	V_IDRESPONSABLEACTA  NUMBER;
	v_idresponsableinforme number;

	v_id_acta  NUMBER;
    v_estado_acta  NUMBER;


	/*  CURSOR CON EL ACTA ACTUAL  */

	  CURSOR cINFORME IS
	    SELECT EV_IN_ID             		ID,
		       EV_IN_IDACTA         		IDACTA,
			   EV_IN_NUMERO            		NUMEROINFORME,
			   EV_IN_FECHAINICIO            FECHAINICIO,
			   EV_IN_FECHAENVIO             FECHAENVIO,
               EV_IN_IDRESPONSABLE			IDRESPONSABLEINFORME,
			   EV_IN_EVALUADOR              EVALUADOR,
			   EV_IN_CARGOEVALUADOR         CARGOEVALUADOR,
               EV_IN_FECHARECEPCIONMUESTRAS	FECHARECEPCION,
               EV_IN_FECHAPREVISIONCIERRE	FECHAPREVISION,
               EV_IN_FECHACIERRE			FECHACIERRE,
			   EV_SM_ID						IDSOLICITUD,
			   NVL(EV_IN_MODIFICAREVALUADOR,'N')	    MODIFICAREVALUADOR,
               EV_IN_EVALUACIONFUNCIONAL	EVALUACIONFUNCIONAL,
			   EV_IN_EVALUACIONENVOLTORIO   EVALUACIONENVOLTORIO,
               EV_IN_COMENTARIOS			COMENTARIOS,
			   EV_IN_COMENT_resp_acta		COMENTARIOS_RESP_ACTA,
			   EV_IN_STATUS					STATUS,
			   EV_IN_PLAZODEVOLUCION        PLAZODEVOLUCION,
               EV_IN_APTO			        APTO,
			   NVL(EV_IN_FICHATECNICA,'N')	FICHATECNICA,
			   NVL(EV_IN_CERTIFICADO,'N')   CERTIFICADO,
			   EV_IN_NUMEROMUESTRASPREVISTAS NUMEROMUESTRASPREVISTAS,
			   NVL(EV_IN_MUESTRASCRITERIO_PROV,'N') MUESTRASCRITERIO_PROV,
			   EV_IN_FECHAPREVISTAMUESTRAS FECHAPREVISTAMUESTRAS,
			   USUARIOINFORME.US_APELLIDO1||' '||USUARIOINFORME.US_APELLIDO2||', '||USUARIOINFORME.US_NOMBRE     RESPONSABLEINFORME,
			   TU_DESCRIPCION  					   CARGORESPONSABLEINFORME,
			   CENTROINFORME.CEN_NOMBRE		CENTRORESPONSABLEINFORME,
			   CP_PV_REFERENCIA     		REFERENCIAPRODUCTO,
			   CP_PV_NOMBREPRODUCTO			NOMBREPRODUCTO,
			   CP_PRO_REFERENCIA			REFERENCIAPRIVADA,
			   CP_PRO_NOMBRE				NOMBREPRIVADO,
			   CP_PRO_DESCRIPCION			DESCRIPCIONPRIVADA,
			   CP_PRO_UDBASE				UNIDADBASICA,
			   CP_PV_IDPROVEEDOR				PROV_ID,
			   CP_PV_NOMBREPROVEEDOR			PROV_NOMBRE,
			   NVL(EV_IN_NUMEROMUESTRAS,'') NUMEROMUESTRAS,
			   EV_AC_IDRESPONSABLE			IDRESPONSABLEACTA,
			   USUARIOACTA.US_APELLIDO1||' '||USUARIOACTA.US_APELLIDO2||', '||USUARIOACTA.US_NOMBRE     RESPONSABLEACTA,
			   CENTROACTA.CEN_NOMBRE		CENTRORESPONSABLEACTA
		  FROM EVALUACION_ACTAS,
		       CATPRIV_PROVEEDORES,
			   CATPRIV_PRODUCTOSESTANDAR,
			   EVALUACION_INFORMES,
			   EVAL_SOLICITUDMUESTRAS,
			   CENTROS CENTROINFORME,
			   CENTROS CENTROACTA,
			   USUARIOS USUARIOACTA,
			   USUARIOS USUARIOINFORME,
			   TIPOSUSUARIOS
		 WHERE EV_IN_ID=P_IDINFORME
		   AND EV_AC_ID=EV_IN_IDACTA
		   AND CP_PV_ID=EV_AC_IDPROVEEDORPRODUCTO
		   AND CP_PRO_ID=CP_PV_IDPRODUCTOESTANDAR
		   AND USUARIOACTA.US_ID=EV_AC_IDRESPONSABLE
		   AND CENTROACTA.CEN_ID=USUARIOACTA.US_IDCENTRO
		   AND USUARIOINFORME.US_ID=EV_IN_IDRESPONSABLE
		   AND CENTROINFORME.CEN_ID=USUARIOINFORME.US_IDCENTRO
		   AND USUARIOINFORME.US_IDTIPO=TU_ID
		   AND EV_IN_ID=EV_SM_IDINFORME(+);

	V_ACCION VARCHAR2(100);

	V_FICHATECNICA VARCHAR2(1);
	V_CERTIFICADO VARCHAR2(1);

	V_STATUS NUMBER;

  BEGIN

    /*  si la accion es null suponemos que es modificar informe */


	V_ACCION:=NVL(P_ACCION,'MODIFICARINFORME');

    /*   PREPARAMOS LOS CHECK   */

	SELECT DECODE(P_CHKCONCLUSION,'P',NULL,P_CHKCONCLUSION),
	       DECODE(P_FICHATECNICA,'on','S','N'),
		   DECODE(P_CERTIFICADO,'on','S','N')
	  INTO V_CHKCONCLUSION,
	       V_FICHATECNICA,
		   V_CERTIFICADO
      FROM DUAL;


    SELECT CEN_IDEMPRESA
    INTO V_IDEMPRESA
    FROM CENTROS,
		 USUARIOS
  WHERE US_ID=P_US_ID
    AND US_IDCENTRO=CEN_ID;



	/*   */

	IF V_ACCION='NUEVOINFORME' THEN

	  /*  LA INSERCIONES SE HACEN EN MODIFICARACTA (INSERTAR NUEVO RESPONSABLE)*/
	  NULL;

	ELSE
	  IF V_ACCION='MODIFICARINFORME' THEN

	    /*

		   MIRAMOS SI EL USUARIO QUE LO ABRE ES EL RESPONSABLE, SI LO ES Y ES LA PRIMERA VEZ (STATUS =10)
		   LO ACTUALIZAMOS A ESTADO RECIBIDO (20)

		*/


		--SELECT EV_IN_IDRESPONSABLE,
		       --EV_IN_STATUS
		  --INTO V_IDRESPONSABLE,
		       --V_ESTADOINFORME
		  --FROM EVALUACION_INFORMES
		 --WHERE EV_IN_ID=P_IDINFORME;

		/*
		   INICIAMOS EL PROCESO DE EVALUACION
		   LA PRIMERA VEZ QUE EL RESPONSABLE DEL INFORME LO ABRE
		   (informe enviado o informe, muestras recibidas)
		*/

		--IF (P_US_ID=V_IDRESPONSABLE) AND (V_ESTADOINFORME=20 or V_ESTADOINFORME=27) THEN

		  --UPDATE EVALUACION_INFORMES
		     --SET EV_IN_STATUS=30,
		         --EV_IN_FECHAINICIO=TO_DATE(SYSDATE)
		   --WHERE EV_IN_ID=P_IDINFORME;

		   --select ev_in_idacta
				     --into v_id_acta
				     --from EVALUACION_INFORMES
					 --where ev_in_id=P_IDINFORME;

				     --v_estado_acta:=OBTENERESTADOACTA(v_id_acta);

				     --update EVALUACION_actas
					    --set ev_ac_status=v_estado_acta
						--where ev_ac_id=v_id_acta;




		   -- actualizamos el workflow
				        --Workflow_Pck.Actualizar (
				         --p_WF_IDESTADO_SET =>30,
				         --p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				         --p_WF_IDRESPONSABLE_SET => V_IDRESPONSABLE,
                         --p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				         --p_WF_SUBCODIGO_SET => NULL,
				         --p_WF_CODIGO_WHERE => P_IDINFORME,
				         --p_WF_SUBCODIGO_WHERE => NULL,
				         --p_WF_IDTIPO_WHERE=>6);

		--END IF;


	    HTP.P(Utilidades_PCK.CabeceraXML);
		HTP.P('<INFORME_EVALUACION>');
	    FOR rINFORME IN cINFORME LOOP
		  HTP.P('<IDINFORME>'||rINFORME.ID||'</IDINFORME>');
		  HTP.P('<IDACTA>'||rINFORME.IDACTA||'</IDACTA>');
		  HTP.P('<NUMEROINFORME>'||rINFORME.NUMEROINFORME||'</NUMEROINFORME>');
		  HTP.P('<FECHAINICIO>'||FORMATO.FORMATOFECHA(rINFORME.FECHAINICIO,2)||'</FECHAINICIO>');
		  HTP.P('<FECHAENVIO>'||FORMATO.FORMATOFECHA(rINFORME.FECHAENVIO,2)||'</FECHAENVIO>');
		  --HTP.P('<FECHARECEPCION>'||FORMATO.FORMATOFECHA(rINFORME.FECHARECEPCION,2)||'</FECHARECEPCION>');
		  HTP.P('<FECHARECEPCIONMUESTRAS>'||FORMATO.FORMATOFECHA(rINFORME.FECHARECEPCION,2)||'</FECHARECEPCIONMUESTRAS>');
		  HTP.P('<FECHAPREVISION>'||FORMATO.FORMATOFECHA(rINFORME.FECHAPREVISION,2)||'</FECHAPREVISION>');
		  HTP.P('<FECHACIERRE>'||FORMATO.FORMATOFECHA(rINFORME.FECHACIERRE,2)||'</FECHACIERRE>');
		  HTP.P('<EVALUACIONFUNCIONAL>'||rINFORME.EVALUACIONFUNCIONAL||'</EVALUACIONFUNCIONAL>');
		  HTP.P('<EVALUACIONENVOLTORIO>'||rINFORME.EVALUACIONENVOLTORIO||'</EVALUACIONENVOLTORIO>');
		  HTP.P('<COMENTARIOS>'||MVM.ScapeHTMLString(rINFORME.COMENTARIOS)||'</COMENTARIOS>');
          HTP.P('<COMENTARIOS_RESP_ACTA_HTML>'||Utilidades_pck.TEXTOHTML(rINFORME.COMENTARIOS_RESP_ACTA)||'</COMENTARIOS_RESP_ACTA_HTML>');
		  HTP.P('<EVALUACIONFUNCIONAL_HTML>'||Utilidades_pck.TEXTOHTML(rINFORME.EVALUACIONFUNCIONAL)||'</EVALUACIONFUNCIONAL_HTML>');
		  HTP.P('<EVALUACIONENVOLTORIO_HTML>'||Utilidades_pck.TEXTOHTML(rINFORME.EVALUACIONENVOLTORIO)||'</EVALUACIONENVOLTORIO_HTML>');
		  HTP.P('<COMENTARIOS_HTML>'||Utilidades_pck.TEXTOHTML(rINFORME.COMENTARIOS)||'</COMENTARIOS_HTML>');
		  HTP.P('<APTO>'||rINFORME.APTO||'</APTO>');
		  HTP.P('<IDRESPONSABLEINFORME>'||rINFORME.IDRESPONSABLEINFORME||'</IDRESPONSABLEINFORME>');
		  HTP.P('<RESPONSABLEINFORME>'||MVM.ScapeHTMLString(rINFORME.RESPONSABLEINFORME)||'</RESPONSABLEINFORME>');
		  HTP.P('<CARGORESPONSABLEINFORME>'||MVM.ScapeHTMLString(rINFORME.CARGORESPONSABLEINFORME)||'</CARGORESPONSABLEINFORME>');
		  HTP.P('<CENTRORESPONSABLEINFORME>'||MVM.ScapeHTMLString(rINFORME.CENTRORESPONSABLEINFORME)||'</CENTRORESPONSABLEINFORME>');


		  HTP.P('<MODIFICAREVALUADOR>'||rINFORME.MODIFICAREVALUADOR||'</MODIFICAREVALUADOR>');

		  HTP.P('<EVALUADOR>'||MVM.ScapeHTMLString(rINFORME.EVALUADOR)||'</EVALUADOR>');
		  HTP.P('<CARGOEVALUADOR>'||MVM.ScapeHTMLString(rINFORME.CARGOEVALUADOR)||'</CARGOEVALUADOR>');
		  HTP.P('<PROV_ID>'||rINFORME.PROV_ID||'</PROV_ID>');
		  HTP.P('<PROV_NOMBRE>'||MVM.ScapeHTMLString(rINFORME.PROV_NOMBRE)||'</PROV_NOMBRE>');
		  HTP.P('<REFERENCIAPRODUCTO>'||rINFORME.REFERENCIAPRODUCTO||'</REFERENCIAPRODUCTO>');
		  HTP.P('<NOMBREPRODUCTO>'||MVM.ScapeHTMLString(rINFORME.NOMBREPRODUCTO)||'</NOMBREPRODUCTO>');
		  HTP.P('<REFERENCIAPRIVADA>'||rINFORME.REFERENCIAPRIVADA||'</REFERENCIAPRIVADA>');
		  HTP.P('<NOMBREPRIVADO>'||MVM.ScapeHTMLString(rINFORME.NOMBREPRIVADO)||'</NOMBREPRIVADO>');
		  HTP.P('<DESCRIPCIONPRIVADA>'||UTILIDADES_PCK.TEXTOHTML(rINFORME.DESCRIPCIONPRIVADA)||'</DESCRIPCIONPRIVADA>');
		  HTP.P('<UNIDADBASICA>'||rINFORME.UNIDADBASICA||'</UNIDADBASICA>');
		  HTP.P('<NUMEROMUESTRAS>'||MVM.ScapeHTMLString(rINFORME.NUMEROMUESTRAS)||'</NUMEROMUESTRAS>');
		  HTP.P('<IDRESPONSABLEACTA>'||rINFORME.IDRESPONSABLEACTA||'</IDRESPONSABLEACTA>');
		  HTP.P('<RESPONSABLEACTA>'||MVM.ScapeHTMLString(rINFORME.RESPONSABLEACTA)||'</RESPONSABLEACTA>');
		  HTP.P('<CENTRORESPONSABLEACTA>'||MVM.ScapeHTMLString(rINFORME.CENTRORESPONSABLEACTA)||'</CENTRORESPONSABLEACTA>');

		  HTP.P('<NUMEROMUESTRASPREVISTAS>'||MVM.ScapeHTMLString(rINFORME.NUMEROMUESTRASPREVISTAS)||'</NUMEROMUESTRASPREVISTAS>');
		  HTP.P('<MUESTRASCRITERIO_PROV>'||rINFORME.MUESTRASCRITERIO_PROV||'</MUESTRASCRITERIO_PROV>');
		  HTP.P('<FECHAPREVISTAMUESTRAS>'||FORMATO.FORMATOFECHA(rINFORME.FECHAPREVISTAMUESTRAS,2)||'</FECHAPREVISTAMUESTRAS>');

		  HTP.P('<PLAZODEVOLUCION>'||rINFORME.PLAZODEVOLUCION||'</PLAZODEVOLUCION>');

		  HTP.P('<FICHATECNICA>'||rINFORME.FICHATECNICA||'</FICHATECNICA>');
		  HTP.P('<CERTIFICADO>'||rINFORME.CERTIFICADO||'</CERTIFICADO>');

		  HTP.P('<STATUS>'||rINFORME.STATUS||'</STATUS>');

		   -- SI TIENE UNA SOLICITUD ASOCIADA LA DEVOLVEMOS
		  -- LA PUEDE CONSULTAR CUALQUIER USUARIO (SOLO LECTURA)

		  IF rINFORME.IDSOLICITUD IS NOT NULL THEN
		    HTP.P('<IDSOLICITUD>'||rINFORME.IDSOLICITUD||'</IDSOLICITUD>');
		  END IF;


		END LOOP;
		  LISTACRITERIOSINFORME(P_IDINFORME,'F');
		  LISTACRITERIOSINFORME(P_IDINFORME,'E');




	    HTP.P('</INFORME_EVALUACION>');

	  ELSE
	     IF V_ACCION='GUARDARINFORME' THEN

		   GUARDARRESPUESTASCRITERIOS(P_IDINFORME,P_CAMBIOSCRITERIOS);

		   SELECT EV_IN_STATUS
		     INTO V_STATUS
			 FROM EVALUACION_INFORMES
			WHERE EV_IN_ID=P_IDINFORME;

		   -- se abre el informe pendiente de solicitud de muestras
		   -- y se guardan los datos, para a muestras recibidas
		   IF NVL(P_NUMEROMUESTRAS,null)is not null AND V_STATUS=15 THEN
		     --V_STATUS:=30;
			 V_STATUS:=27;
		   ELSE
		     V_STATUS:=V_STATUS;
		   END IF;

		   UPDATE EVALUACION_INFORMES
		      SET EV_IN_FECHARECEPCIONMUESTRAS=TO_DATE(P_FECHARECEPCIONMUESTRAS,'DD/MM/YYYY'),
			      EV_IN_FECHAPREVISIONCIERRE=TO_DATE(P_FECHAPREVISION,'DD/MM/YYYY'),
				  EV_IN_EVALUACIONFUNCIONAL=P_EVALUACIONFUNCIONAL,
				  EV_IN_EVALUACIONENVOLTORIO=P_EVALUACIONENVOLTORIO,
				  EV_IN_COMENTARIOS=P_COMENTARIOS,
				  EV_IN_APTO=V_CHKCONCLUSION,
				  EV_IN_EVALUADOR=P_EVALUADORINFORME,
				  EV_IN_CARGOEVALUADOR=P_CARGOEVALUADORINFORME,
				  EV_IN_NUMEROMUESTRAS=P_NUMEROMUESTRAS,
				  EV_IN_FICHATECNICA=V_FICHATECNICA,
				  EV_IN_CERTIFICADO=V_CERTIFICADO,
				  EV_IN_STATUS=V_STATUS
			WHERE EV_IN_ID=P_IDINFORME;

			select ev_in_idacta
				     into v_id_acta
				     from EVALUACION_INFORMES
					 where ev_in_id=P_IDINFORME;

				     v_estado_acta:=OBTENERESTADOACTA(v_id_acta);

				     update EVALUACION_actas
					    set ev_ac_status=v_estado_acta
						where ev_ac_id=v_id_acta;


			V_ESTADOINFORME:=OBTENERESTADOINFORME(P_IDINFORME);


			 -- SOLO ACTUALIZAMOS EL WORFLOW SI EL INFORME ESTA EN EL ESTADO 30
			 -- (EN CURSO)

			IF V_ESTADOINFORME=30 THEN

			SELECT EV_IN_IDRESPONSABLE
		      INTO V_IDRESPONSABLE
		      FROM EVALUACION_INFORMES
		    WHERE EV_IN_ID=P_IDINFORME;

			 --actualizamos el workflow
				        Workflow_Pck.Actualizar (
				         p_WF_IDESTADO_SET =>V_ESTADOINFORME,
				         p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				         p_WF_IDRESPONSABLE_SET => V_IDRESPONSABLE,
                         p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				         p_WF_SUBCODIGO_SET => NULL,
				         p_WF_CODIGO_WHERE => P_IDINFORME,
				         p_WF_SUBCODIGO_WHERE => NULL,
				         p_WF_IDTIPO_WHERE=>6);

			END IF;

		 ELSE
           IF V_ACCION='CERRARINFORME' THEN

		     GUARDARRESPUESTASCRITERIOS(P_IDINFORME,P_CAMBIOSCRITERIOS);

		     UPDATE EVALUACION_INFORMES
		      SET EV_IN_FECHARECEPCIONMUESTRAS=TO_DATE(P_FECHARECEPCIONMUESTRAS,'DD/MM/YYYY'),
			      EV_IN_FECHAPREVISIONCIERRE=TO_DATE(P_FECHAPREVISION,'DD/MM/YYYY'),
				  EV_IN_EVALUACIONFUNCIONAL=P_EVALUACIONFUNCIONAL,
				  EV_IN_EVALUACIONENVOLTORIO=P_EVALUACIONENVOLTORIO,
				  EV_IN_COMENTARIOS=P_COMENTARIOS,
				  EV_IN_APTO=V_CHKCONCLUSION,
				  EV_IN_EVALUADOR=P_EVALUADORINFORME,
				  EV_IN_CARGOEVALUADOR=P_CARGOEVALUADORINFORME,
				  EV_IN_STATUS=40,
				  EV_IN_FECHACIERRE=TO_DATE(SYSDATE),
				  EV_IN_NUMEROMUESTRAS=P_NUMEROMUESTRAS
			WHERE EV_IN_ID=P_IDINFORME;


			select ev_in_idacta
				     into v_id_acta
				     from EVALUACION_INFORMES
					 where ev_in_id=P_IDINFORME;

				     v_estado_acta:=OBTENERESTADOACTA(v_id_acta);

				     update EVALUACION_actas
					    set ev_ac_status=v_estado_acta
						where ev_ac_id=v_id_acta;


			SELECT EV_AC_IDRESPONSABLE
		      INTO V_IDRESPONSABLEACTA
		      FROM EVALUACION_INFORMES,
			       EVALUACION_ACTAS
		     WHERE EV_IN_ID=P_IDINFORME
			   AND EV_AC_ID=EV_IN_IDACTA;

			-- actualizamos el workflow
				        Workflow_Pck.Actualizar (
				         p_WF_IDESTADO_SET =>40,
				         p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				         p_WF_IDRESPONSABLE_SET => V_IDRESPONSABLEACTA,
                         p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				         p_WF_SUBCODIGO_SET => NULL,
				         p_WF_CODIGO_WHERE => P_IDINFORME,
				         p_WF_SUBCODIGO_WHERE => NULL,
				         p_WF_IDTIPO_WHERE=>6);

		   ELSE

			 IF V_ACCION='ARCHIVARINFORME' THEN

			   UPDATE EVALUACION_INFORMES
		      SET EV_IN_STATUS=50
			WHERE EV_IN_ID=P_IDINFORME;

			select ev_in_idacta
				     into v_id_acta
				     from EVALUACION_INFORMES
					 where ev_in_id=P_IDINFORME;

				     v_estado_acta:=OBTENERESTADOACTA(v_id_acta);

				     update EVALUACION_actas
					    set ev_ac_status=v_estado_acta
						where ev_ac_id=v_id_acta;

			SELECT EV_AC_IDRESPONSABLE,
			       EV_IN_IDRESPONSABLE
		      INTO V_IDRESPONSABLEACTA,
			       V_IDRESPONSABLEINFORME
		      FROM EVALUACION_INFORMES,
			       EVALUACION_ACTAS
		     WHERE EV_IN_ID=P_IDINFORME
			   AND EV_AC_ID=EV_IN_IDACTA;

			-- actualizamos el workflow
				        Workflow_Pck.Actualizar (
				         p_WF_IDESTADO_SET =>50,
				         p_WF_IDEMPRESA_SET =>V_IDEMPRESA,
				         p_WF_IDRESPONSABLE_SET => V_IDRESPONSABLEINFORME,
                         p_WF_FECHA_ENTRADA_SET => TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI'),
				         p_WF_SUBCODIGO_SET => NULL,
				         p_WF_CODIGO_WHERE => P_IDINFORME,
				         p_WF_SUBCODIGO_WHERE => NULL,
				         p_WF_IDTIPO_WHERE=>6);

		     ELSE

			   NULL;

	         END IF;
		   END IF;
		 END IF;

      END IF;
	END IF;



	IF V_ACCION='GUARDARINFORME' THEN

	      HTP.P('<Status>');
		  HTP.P('<GUARDADO/>');
		  HTP.P('</Status>');

	  --MODIFICARINFORME(
	    --P_US_ID,
	    --P_IDINFORME,
		--P_EVALUADORINFORME,
		--P_CARGOEVALUADORINFORME,
		--P_NUMEROMUESTRAS,
        --P_FECHARECEPCION,
        --P_FECHAPREVISION,
        --P_EVALUACIONFUNCIONAL,
        --P_EVALUACIONENVOLTORIO,
        --P_COMENTARIOS,
        --P_CHKCONCLUSION,
        --P_FECHACIERRE,
		--P_FECHARECEPCIONMUESTRAS,
        --P_FICHATECNICA,
        --P_CERTIFICADO,
		--P_CAMBIOSCRITERIOS,
	    --'MODIFICARINFORME'
	  --);

	ELSE
	  IF V_ACCION='CERRARINFORME' THEN
	    HTP.P('<Status>');
		HTP.P('<CERRADO/>');
		HTP.P('</Status>');

	  ELSE

		IF V_ACCION='ARCHIVARINFORME' THEN
	      HTP.P('<Status>');
		  HTP.P('<ARCHIVADO/>');
		  HTP.P('</Status>');

		END IF;

	  END IF;

	END IF;

	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.MODIFICARINFORME',' ',sqlcode,sqlerrm,NULL);




  END;







  /*


  */


  PROCEDURE LISTARESPONSABLESEVALUACION(
    P_IDEMPRESA IN NUMBER,
	P_IDUSUARIO IN NUMBER DEFAULT -1,
	p_ActivarEventoOnChange IN VARCHAR DEFAULT NULL
  ) IS

	CURSOR cRESPONSABLESACTAS IS
	  SELECT US_ID ID,
	         US_APELLIDO1||' '||US_APELLIDO2||', '||US_NOMBRE||' -- '||CEN_NOMBRE NOMBRE
		FROM USUARIOS,
		     CENTROS
	   WHERE P_IDEMPRESA=CEN_IDEMPRESA
	     AND CEN_ID=US_IDCENTRO
		 AND US_STATUS IS NULL
		 AND CEN_STATUS IS NULL
	ORDER BY UPPER(US_APELLIDO1), UPPER(US_APELLIDO2), UPPER(US_NOMBRE), UPPER(CEN_NOMBRE);

	BEGIN

	  HTP.P('<RESPONSABLESEVALUACION>');
      IF p_ActivarEventoOnChange='S' THEN
		HTP.P('<field name="IDRESPONSABLEEVALUACION" onChange="CambioResponsableEvaluacionActual(this.value,'||'&'||'quot;CAMBIORESPONSABLE'||'&'||'quot;);" current="'||P_IDUSUARIO||'">');
	  ELSE
		HTP.P('<field name="IDRESPONSABLEEVALUACION" current="'||P_IDUSUARIO||'">');
	  END IF;
	  HTP.P('<dropDownList>');
	  FOR rRESPONSABLESACTAS IN cRESPONSABLESACTAS LOOP
		HTP.P('<listElem>');
		HTP.P('<ID>'||rRESPONSABLESACTAS.ID||'</ID>');
		HTP.P('<listItem>'||MVM.ScapeHTMLString(rRESPONSABLESACTAS.NOMBRE)||'</listItem>');
		HTP.P('</listElem>');
	  END LOOP;
	  HTP.P('</dropDownList>');
	  HTP.P('</field>');
	HTP.P('</RESPONSABLESEVALUACION>');

	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.LISTARESPONSABLESEVALUACION',' ',sqlcode,sqlerrm,NULL);

	END;



  /*


  */

  PROCEDURE LISTARESPONSABLESACTA(
    P_IDEMPRESA IN NUMBER,
	P_IDUSUARIO IN NUMBER DEFAULT -1,
	p_ActivarEventoOnChange IN VARCHAR DEFAULT NULL
  ) IS

	CURSOR cRESPONSABLESACTAS IS
	  SELECT US_ID ID,
	         US_APELLIDO1||' '||US_APELLIDO2||', '||US_NOMBRE||' -- '||CEN_NOMBRE NOMBRE
		FROM USUARIOS,
		     CENTROS
	   WHERE P_IDEMPRESA=CEN_IDEMPRESA
	     AND CEN_ID=US_IDCENTRO
		 AND US_STATUS IS NULL
		 AND CEN_STATUS IS NULL
	ORDER BY UPPER(US_APELLIDO1), UPPER(US_APELLIDO2), UPPER(US_NOMBRE), UPPER(CEN_NOMBRE);

	BEGIN

	  HTP.P('<RESPONSABLESACTA>');
      IF p_ActivarEventoOnChange='S' THEN
		HTP.P('<field name="IDRESPONSABLEACTA" onChange="CambioResponsableActaActual(this.value,'||'&'||'quot;CAMBIORESPONSABLE'||'&'||'quot;);" current="'||P_IDUSUARIO||'">');
	  ELSE
		HTP.P('<field name="IDRESPONSABLEACTA" current="'||P_IDUSUARIO||'">');
	  END IF;
	  HTP.P('<dropDownList>');
	  FOR rRESPONSABLESACTAS IN cRESPONSABLESACTAS LOOP
		HTP.P('<listElem>');
		HTP.P('<ID>'||rRESPONSABLESACTAS.ID||'</ID>');
		HTP.P('<listItem>'||MVM.ScapeHTMLString(rRESPONSABLESACTAS.NOMBRE)||'</listItem>');
		HTP.P('</listElem>');
	  END LOOP;
	  HTP.P('</dropDownList>');
	  HTP.P('</field>');
	HTP.P('</RESPONSABLESACTA>');

	EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.LISTARESPONSABLESACTA',' ',sqlcode,sqlerrm,NULL);

	END;


	PROCEDURE INFORMESEVALUACION(
	  P_IDACTA IN NUMBER
	)

	IS

	  CURSOR cINFORMES IS
	    SELECT EV_IN_ID ID,
		       EV_IN_IDRESPONSABLE IDRESPONSABLE,
			   US_APELLIDO1||' '||US_APELLIDO2||', '||US_NOMBRE NOMBRE,
			   TU_DESCRIPCION  					   CARGO,
			   CEN_ID IDCENTRO,
			   CEN_NOMBRE CENTRO,
			   DECODE(EV_IN_APTO,NULL,'Pendiente',EV_IN_APTO) APTO,
			   EV_IN_STATUS    IDSTATUS,
			   ev_sm_id		   idsolicitud,
			   EV_EST_NOMBRE   NOMBRESTATUS,
			   EV_IN_EVALUADOR   EVALUADOR,
			   EV_IN_CARGOEVALUADOR    CARGOEVALUADOR,
			   --EV_IN_COMENT_RESP_ACTA  COMENT_RESP_ACTA,
			   EV_IN_PLAZODEVOLUCION    PLAZODEVOLUCION,
			   nvl(EV_IN_MUESTRASCRITERIO_PROV,'N')   MUESTRASCRITERIO_PROV,
			   ev_in_numerOmuestrasprevistas numerOmuestrasprevistas,
               EV_IN_FECHAprevistaMUESTRAS  FECHAprevistaMUESTRAS,
			   NVL(EV_IN_NUMEROMUESTRAS,NULL) NUMEROMUESTRAS
		  FROM EVALUACION_INFORMES,
		       eval_solicitudmuestras,
		       USUARIOS,
			   CENTROS,
			   TIPOSUSUARIOS,
			   CATPRIV_ESTADOS
		 WHERE EV_IN_IDACTA=P_IDACTA
		   AND EV_EST_ID=EV_IN_STATUS
		   AND EV_IN_IDRESPONSABLE=US_ID
		   AND US_IDCENTRO=CEN_ID
		   AND US_IDTIPO=TU_ID
		   and ev_in_id=ev_sm_idinforme(+)
	  ORDER BY UPPER(US_APELLIDO1), UPPER(US_APELLIDO2),UPPER(US_NOMBRE), UPPER(CEN_NOMBRE);




	BEGIN

	  HTP.P('<INFORMES>');
	    FOR rINFORME IN cINFORMES LOOP
	    HTP.P('<INFORME>');
		  HTP.P('<IDINFORME>'||rINFORME.ID||'</IDINFORME>');
		  HTP.P('<IDSOLICITUD>'||rINFORME.idsolicitud||'</IDSOLICITUD>');

		  HTP.P('<IDRESPONSABLE>'||rINFORME.IDRESPONSABLE||'</IDRESPONSABLE>');
		  HTP.P('<NOMBRERESPONSABLE>'||MVM.ScapeHTMLString(rINFORME.NOMBRE)||'</NOMBRERESPONSABLE>');
		  HTP.P('<CARGORESPONSABLE>'||MVM.ScapeHTMLString(rINFORME.CARGO)||'</CARGORESPONSABLE>');
		  HTP.P('<IDCENTRO>'||rINFORME.IDCENTRO||'</IDCENTRO>');
		  HTP.P('<NOMBRECENTRO>'||MVM.ScapeHTMLString(rINFORME.CENTRO)||'</NOMBRECENTRO>');
		  HTP.P('<EVALUADOR>'||MVM.ScapeHTMLString(rINFORME.EVALUADOR)||'</EVALUADOR>');
		  HTP.P('<CARGOEVALUADOR>'||MVM.ScapeHTMLString(rINFORME.CARGOEVALUADOR)||'</CARGOEVALUADOR>');
		  HTP.P('<IDSTATUS>'||rINFORME.IDSTATUS||'</IDSTATUS>');
		  HTP.P('<APTO>'||rINFORME.APTO||'</APTO>');

		  IF rINFORME.NUMEROMUESTRAS IS NOT NULL THEN
		    HTP.P('<NUMEROMUESTRAS>'||MVM.ScapeHTMLString(rINFORME.NUMEROMUESTRAS)||'</NUMEROMUESTRAS>');
		  ELSE
			HTP.P('<NUMEROMUESTRAS></NUMEROMUESTRAS>');
		  END IF;

		  HTP.P('<NUMEROMUESTRASPREVISTAS>'||MVM.ScapeHTMLString(rINFORME.numerOmuestrasprevistas)||'</NUMEROMUESTRASPREVISTAS>');

		  HTP.P('<MUESTRASCRITERIO_PROV>'||rINFORME.MUESTRASCRITERIO_PROV||'</MUESTRASCRITERIO_PROV>');

		  HTP.P('<FECHAPREVISTAMUESTRAS>'||Formato.FormatoFecha(rINFORME.FECHAPREVISTAMUESTRAS,2)||'</FECHAPREVISTAMUESTRAS>');

		  HTP.P('<PLAZODEVOLUCION>'||rINFORME.PLAZODEVOLUCION||'</PLAZODEVOLUCION>');
		  HTP.P('<NOMBRESTATUS>'||rINFORME.NOMBRESTATUS||'</NOMBRESTATUS>');
		  --HTP.P('<COMENTARIOSRESPONSABLEACTA>'||MVM.ScapeHTMLString(rINFORME.COMENT_RESP_ACTA)||'</COMENTARIOSRESPONSABLEACTA>');
		  --HTP.P('<COMENTARIOSRESPONSABLEACTA_HTML>'||Utilidades_pck.TEXTOHTML(rINFORME.COMENT_RESP_ACTA)||'</COMENTARIOSRESPONSABLEACTA_HTML>');
		HTP.P('</INFORME>');
		END LOOP;
	  HTP.P('</INFORMES>');


	 EXCEPTION
    WHEN OTHERS THEN

	  HTP.P('<ERROR/>');
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.INFORMESEVALUACION',' ',sqlcode,sqlerrm,NULL);

	END;

	/*


	*/

	PROCEDURE BORRARINFORME(
	  P_US_ID		  IN NUMBER,
		P_IDINFORME IN NUMBER
	)

	IS

	BEGIN

	  BORRARRESPUESTASINFORME(P_IDINFORME);


	  DELETE EVALUACION_INFORMES
	  WHERE EV_IN_ID=P_IDINFORME;

		LOGADMINISTRACION_PCK.Insertar(P_US_ID,3,'EVALUACION_INFORMES',P_IDINFORME,'BORRAR INFORME');

	  EXCEPTION
    WHEN OTHERS THEN

	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.BORRARINFORME',' ',sqlcode,sqlerrm,NULL);

	END;

   /*


   */


   PROCEDURE BORRARANEXO(
	  P_IDANEXO IN NUMBER
	)

	IS

	BEGIN
	  DELETE EVALUACION_ANEXOSACTAS
	  WHERE EV_AAC_ID=P_IDANEXO;

	    EXCEPTION
    WHEN OTHERS THEN

	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.BORRARANEXO',' ',sqlcode,sqlerrm,NULL);
	END;





  PROCEDURE CREARANEXOSACTA(
    P_IDACTA IN NUMBER
  )

  IS
    V_IDANEXO NUMBER;
	V_FECHA_RECEPCION DATE;
	V_FECHA_PREVISTA  DATE;
    V_IDPREVISTA      NUMBER;
	V_OK VARCHAR2(1);

  BEGIN


	/* MUESTRAS*/

	--SELECT NVL(MAX(EV_AAC_ID),0)+1
	  --INTO V_IDANEXO
	  --FROM EVALUACION_ANEXOSACTAS;

	SELECT EVALUACION_ANEXOSACTAS_SEQ.NEXTVAL
	  INTO V_IDANEXO
	  FROM DUAL;



    --SELECT NVL(CP_PV_MUESTRAS,'N')
	--  INTO V_OK
	--  FROM CATPRIV_PROVEEDORES,
    --       EVALUACION_ACTAS
	-- WHERE EV_AC_ID=P_IDACTA
	--   AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID;

	--   IF V_OK='S' THEN
	--     V_FECHA_RECEPCION:=TO_DATE(SYSDATE);
	--	 V_FECHA_PREVISTA:=TO_DATE(SYSDATE);
	--	 V_IDPREVISTA:=999;
	--   ELSE
	--     V_FECHA_RECEPCION:=NULL;
	--	 V_FECHA_PREVISTA:=NULL;
	--	 V_IDPREVISTA:=7;
	--   END IF;




	INSERT INTO EVALUACION_ANEXOSACTAS(
	  EV_AAC_ID,
	  EV_AAC_IDACTA,
	  EV_AAC_TIPOANEXO,
	  EV_AAC_FECHASOLICITUD,
	  EV_AAC_PREVISTAENTREGA,
	  EV_AAC_FECHAENTREGA,
	  EV_AAC_IDPREVISTAENTREGA
	)
	VALUES(
	  V_IDANEXO,
	  P_IDACTA,
	  'Muestras',
	  --SYSDATE,
	  --V_FECHA_PREVISTA,
	  --V_FECHA_RECEPCION,
	  --V_IDPREVISTA
	  NULL,
	  NULL,
	  NULL,
	  NULL
	);

	/*  FICHA TECNICA*/

	--SELECT NVL(MAX(EV_AAC_ID),0)+1
	  --INTO V_IDANEXO
	  --FROM EVALUACION_ANEXOSACTAS;

	--	SELECT EVALUACION_ANEXOSACTAS_SEQ.NEXTVAL
	--  INTO V_IDANEXO
	--  FROM DUAL;

	 --SELECT NVL(CP_PV_FICHATECNICA,'N')
	 -- INTO V_OK
	 -- FROM CATPRIV_PROVEEDORES,
     --      EVALUACION_ACTAS
	 --WHERE EV_AC_ID=P_IDACTA
	   --AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID;

	 --IF V_OK='S' THEN
	 --    V_FECHA_RECEPCION:=TO_DATE(SYSDATE);
---		 V_FECHA_PREVISTA:=TO_DATE(SYSDATE);
--		 V_IDPREVISTA:=999;
--	   ELSE
	--     V_FECHA_RECEPCION:=NULL;
	--	 V_FECHA_PREVISTA:=NULL;
--		 V_IDPREVISTA:=7;
--	   END IF;

--	INSERT INTO EVALUACION_ANEXOSACTAS(
	--  EV_AAC_ID,
	--  EV_AAC_IDACTA,
	--  EV_AAC_TIPOANEXO,
	--  EV_AAC_FECHASOLICITUD,
	--  EV_AAC_PREVISTAENTREGA,
	--  EV_AAC_FECHAENTREGA,
	--  EV_AAC_IDPREVISTAENTREGA
--	)
--	VALUES(
--	  V_IDANEXO,
--	  P_IDACTA,
--	  'Ficha Técnica',
--	  SYSDATE,
--	  V_FECHA_PREVISTA,
--	  V_FECHA_RECEPCION,
--	  V_IDPREVISTA
--	);

	/*   CERTIFICADO  */

	--SELECT NVL(MAX(EV_AAC_ID),0)+1
	  --INTO V_IDANEXO
	  --FROM EVALUACION_ANEXOSACTAS;

--		SELECT EVALUACION_ANEXOSACTAS_SEQ.NEXTVAL
--	  INTO V_IDANEXO
--	  FROM DUAL;

--	 SELECT NVL(CP_PV_CERTIFICADO,'N')
--	  INTO V_OK
--	  FROM CATPRIV_PROVEEDORES,
 --          EVALUACION_ACTAS
--	 WHERE EV_AC_ID=P_IDACTA
--	   AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID;

--	 IF V_OK='S' THEN
--	     V_FECHA_RECEPCION:=TO_DATE(SYSDATE);
--		 V_FECHA_PREVISTA:=TO_DATE(SYSDATE);
--		 V_IDPREVISTA:=999;
--	   ELSE
--	     V_FECHA_RECEPCION:=NULL;
--		 V_FECHA_PREVISTA:=NULL;
--		 V_IDPREVISTA:=7;
--	   END IF;


--	INSERT INTO EVALUACION_ANEXOSACTAS(
--	  EV_AAC_ID,
--	  EV_AAC_IDACTA,
--	  EV_AAC_TIPOANEXO,
--	  EV_AAC_FECHASOLICITUD,
--	  EV_AAC_PREVISTAENTREGA,
--	  EV_AAC_FECHAENTREGA,
--	  EV_AAC_IDPREVISTAENTREGA
--	)
--	VALUES(
--	  V_IDANEXO,
--	  P_IDACTA,
--	  'Certificado CE',
--	  SYSDATE,
--	  V_FECHA_PREVISTA,
--	  V_FECHA_RECEPCION,
--	  V_IDPREVISTA
--	);

	EXCEPTION


	    WHEN OTHERS THEN


		 MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.CREARANEXOSACTA ',' ',sqlcode,sqlerrm,NULL);


  END;


  /*



  */

  PROCEDURE ACTUALIZARANEXOS(
    P_ANEXOS IN VARCHAR2
  )
  IS

    V_CADENA VARCHAR2(3000);

	V_IDANEXO          NUMBER;
	V_FECHASOLICITUD   VARCHAR2(11);
	V_FECHAPREVISTA    VARCHAR2(11);
	V_FECHAENTREGA     VARCHAR2(11);
	V_COMENTARIOS      VARCHAR2(3000);
	V_IDFECHAPREVISTA  NUMBER;
	V_RECIBIDO         VARCHAR2(1);

	V_TIPOANEXO EVALUACION_ANEXOSACTAS.EV_AAC_TIPOANEXO%TYPE;
	V_IDPROVEEDORPRODUCTO CATPRIV_PROVEEDORES.CP_PV_ID%TYPE;

	V_MUESTRAS VARCHAR2(1);
	V_FICHA VARCHAR2(1);
	V_CERTIFICADO VARCHAR2(1);

  BEGIN

    IF	P_ANEXOS IS NOT NULL THEN




		FOR I IN 0..Utilidades_PCK.PieceCount(P_ANEXOS,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_ANEXOS,'#',I);

			V_IDANEXO:=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			V_FECHASOLICITUD:=Utilidades_PCK.Piece(V_CADENA,'|',1);
			V_FECHAPREVISTA:=Utilidades_PCK.Piece(V_CADENA,'|',2);
			V_FECHAENTREGA:=Utilidades_PCK.Piece(V_CADENA,'|',3);
			V_COMENTARIOS:=Utilidades_PCK.Piece(V_CADENA,'|',4);
			V_IDFECHAPREVISTA:=Utilidades_PCK.Piece(V_CADENA,'|',5);
			V_RECIBIDO:=Utilidades_PCK.Piece(V_CADENA,'|',6);


			-- OBTENEMOS EL TIPO DE ANEXO (CE, FICHA TECNICA, MUESTRAS)
			-- Y EL ID DEL PROVEEDOR DEL PRODUCTO

			SELECT EV_AAC_TIPOANEXO,
				   CP_PV_ID
			  INTO V_TIPOANEXO,
			       V_IDPROVEEDORPRODUCTO
			  FROM EVALUACION_ANEXOSACTAS,
			       EVALUACION_ACTAS,
				   CATPRIV_PROVEEDORES
			 WHERE EV_AAC_ID=V_IDANEXO
			   AND EV_AC_ID=EV_AAC_IDACTA
			   AND CP_PV_ID=EV_AC_IDPROVEEDORPRODUCTO;


			-- ALMACENAMOS LOS CHECK RECIBIDO EN VARIABLES
			-- HACEMOS UNA SOLA ACTUALIZACION CUANDO ESTAN TODOS INFORMADOS

		    IF V_TIPOANEXO='Muestras' THEN

			  V_MUESTRAS:=V_RECIBIDO;

			ELSE
			  IF V_TIPOANEXO='Ficha Técnica' THEN

			    V_FICHA:=V_RECIBIDO;

			  ELSE
			    IF V_TIPOANEXO='Certificado CE' THEN

				  V_CERTIFICADO:=V_RECIBIDO;

				ELSE

				  NULL;

				END IF;

			  END IF;

			END IF;



			UPDATE EVALUACION_ANEXOSACTAS
			   SET EV_AAC_FECHASOLICITUD=TO_DATE(V_FECHASOLICITUD,'DD/MM/YYYY'),
			       EV_AAC_PREVISTAENTREGA=TO_DATE(V_FECHAPREVISTA,'DD/MM/YYYY'),
				   EV_AAC_IDPREVISTAENTREGA=V_IDFECHAPREVISTA,
				   EV_AAC_FECHAENTREGA=TO_DATE(V_FECHAENTREGA,'DD/MM/YYYY'),
				   EV_AAC_COMENTARIOS=V_COMENTARIOS
			 WHERE EV_AAC_ID=V_IDANEXO;




		END LOOP;

		-- ACTUALIZAMOS LOS CHECK

		UPDATE CATPRIV_PROVEEDORES
		   SET CP_PV_MUESTRAS=V_MUESTRAS,
		       CP_PV_FICHATECNICA=V_FICHA,
			   CP_PV_CERTIFICADO=V_CERTIFICADO
		 WHERE CP_PV_ID=V_IDPROVEEDORPRODUCTO;

	END IF;

	EXCEPTION


	    WHEN OTHERS THEN

		 MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.ACTUALIZARANEXOS',' ',sqlcode,sqlerrm,NULL);

  END;


  PROCEDURE ACTUALIZARINFORMES(
    P_CAMBIOS_INFORMES IN VARCHAR2
  )
  IS

    V_CADENA VARCHAR2(3000);

	V_IDINFORME          NUMBER;
	--V_COMENTARIOS      VARCHAR2(3000);
	V_EVALUADOR     VARCHAR2(500);
	V_CARGOEVALUADOR      VARCHAR2(500);
	V_NUMEROMUESTRAS      varchar2(100);
	V_PLAZODEVOLUCION      NUMBER;

  BEGIN

    IF	P_CAMBIOS_INFORMES IS NOT NULL THEN

		FOR I IN 0..Utilidades_PCK.PieceCount(P_CAMBIOS_INFORMES,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_CAMBIOS_INFORMES,'#',I);

			V_IDINFORME:=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			--V_COMENTARIOS:=Utilidades_PCK.Piece(V_CADENA,'|',1);
			V_EVALUADOR:=Utilidades_PCK.Piece(V_CADENA,'|',1);
	        V_CARGOEVALUADOR:=Utilidades_PCK.Piece(V_CADENA,'|',2);
			V_NUMEROMUESTRAS:=Utilidades_PCK.Piece(V_CADENA,'|',3);
			V_PLAZODEVOLUCION:=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',4));

			UPDATE EVALUACION_INFORMES
			   SET --EV_IN_COMENT_RESP_ACTA=V_COMENTARIOS,
			       EV_IN_EVALUADOR=V_EVALUADOR,
				   EV_IN_CARGOEVALUADOR=V_CARGOEVALUADOR,
				   EV_IN_NUMEROMUESTRASPREVISTAS=V_NUMEROMUESTRAS,
				   EV_IN_PLAZODEVOLUCION=V_PLAZODEVOLUCION
			 WHERE EV_IN_ID=V_IDINFORME;

		END LOOP;

	END IF;

	EXCEPTION


	    WHEN OTHERS THEN

		 MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.ACTUALIZARINFORMES',' ',sqlcode,sqlerrm,NULL);

  END;








  FUNCTION OBTENER_ETIQUETA_ESTADO(
    P_ID IN NUMBER
  ) RETURN VARCHAR2

  IS

    V_ETIQUETA CATPRIV_ESTADOS.EV_EST_NOMBRE%TYPE;

  BEGIN

    SELECT EV_EST_NOMBRE
	  INTO V_ETIQUETA
	  FROM CATPRIV_ESTADOS
	 WHERE EV_EST_ID=P_ID;


	RETURN V_ETIQUETA;

  END;


  /*


  */

  PROCEDURE MODIFICARCRITERIOSGENERALES(
    P_US_ID              IN NUMBER,
    P_IDCRITERIO         IN NUMBER,
	P_DESCRIPCION        IN VARCHAR2,
    P_TIPOCRITERIO       IN VARCHAR2,
	P_ACCION             IN VARCHAR2
  ) IS

    V_ACCION VARCHAR2(100);
	V_IDEMPRESA EMPRESAS.EMP_ID%TYPE;

	V_IDCRITERIO EVALUACION_CRITERIOSGENERALES.EV_CG_ID%TYPE;


	CURSOR cCRITERIO IS
	  SELECT EV_CG_ID IDCRITERIO,
	         EV_CG_DESCRIPCION DESCRIPCIONCRITERIO,
			 EV_CG_TIPO TIPOCRITERIO
		FROM EVALUACION_CRITERIOSGENERALES
	   WHERE EV_CG_ID=P_IDCRITERIO;


  BEGIN

    V_ACCION:=NVL(P_ACCION,'ANYADIRCRITERIO');

	V_IDEMPRESA:=Utilidades_PCK.EmpresaDelUsuario(P_US_ID);


	IF V_ACCION='ANYADIRCRITERIO' THEN

	  HTP.P(Utilidades_PCK.CabeceraXML);
	  HTP.P('<CRITERIOS>');
	  HTP.P('<CRITERIOACTUAL>');
	    HTP.P('<IDEMPRESA>'||V_IDEMPRESA||'</IDEMPRESA>');
		HTP.P('<IDCRITERIO>0</IDCRITERIO>');
	    HTP.P('<DESCRIPCION></DESCRIPCION>');
	    HTP.P('<TIPO>'||P_TIPOCRITERIO||'</TIPO>');
	  HTP.P('</CRITERIOACTUAL>');
	  LISTACRITERIOSGENERALES(P_US_ID,'F');
	  LISTACRITERIOSGENERALES(P_US_ID,'E');
	  HTP.P('</CRITERIOS>');

	ELSE

	  IF V_ACCION='INSERTARCRITERIO' THEN


		  --SELECT NVL(MAX(EV_CG_ID),0)+1
		    --INTO V_IDCRITERIO
		    --FROM EVALUACION_CRITERIOSGENERALES;

			SELECT EVALUACION_CRITGENERALES_SEQ.NEXTVAL
		    INTO V_IDCRITERIO
		    FROM DUAL;


		  INSERT INTO EVALUACION_CRITERIOSGENERALES(
		    EV_CG_ID,
		    EV_CG_IDEMPRESA,
		    EV_CG_DESCRIPCION,
		    EV_CG_TIPO
		  )
		  VALUES(
		    V_IDCRITERIO,
		    V_IDEMPRESA,
		    P_DESCRIPCION,
		    P_TIPOCRITERIO
		  );

			LOGADMINISTRACION_PCK.Insertar(P_US_ID,1,'EVALUACION_CRITERIOSGENERALES',V_IDCRITERIO,'INSERTAR CRITERIO GENERAL');

	  ELSE

	    IF V_ACCION='BORRARCRITERIO' THEN


		    DELETE EVALUACION_CRITERIOSGENERALES
		     WHERE EV_CG_ID=P_IDCRITERIO;

				 LOGADMINISTRACION_PCK.Insertar(P_US_ID,3,'EVALUACION_CRITERIOSGENERALES',P_IDCRITERIO,'BORRAR CRITERIO GENERAL');

		ELSE

			IF V_ACCION='MODIFICARCRITERIO' THEN


			    HTP.P(Utilidades_PCK.CabeceraXML);
	            HTP.P('<CRITERIOS>');
			      FOR rCRITERIO IN cCRITERIO LOOP
	                HTP.P('<CRITERIOACTUAL>');
	                HTP.P('<IDEMPRESA>'||V_IDEMPRESA||'</IDEMPRESA>');
		            HTP.P('<IDCRITERIO>'||rCRITERIO.IDCRITERIO||'</IDCRITERIO>');
	                HTP.P('<DESCRIPCION>'||MVM.ScapeHTMLString(rCRITERIO.DESCRIPCIONCRITERIO)||'</DESCRIPCION>');
	                HTP.P('<TIPO>'||rCRITERIO.TIPOCRITERIO||'</TIPO>');
	                HTP.P('</CRITERIOACTUAL>');
				  END LOOP;
				  LISTACRITERIOSGENERALES(P_US_ID,'F',P_IDCRITERIO);
	              LISTACRITERIOSGENERALES(P_US_ID,'E',P_IDCRITERIO);
	            HTP.P('</CRITERIOS>');


		  ELSE

			IF V_ACCION='GUARDARCRITERIO' THEN


		        UPDATE EVALUACION_CRITERIOSGENERALES
			       SET EV_CG_DESCRIPCION=P_DESCRIPCION,
				       EV_CG_TIPO=P_TIPOCRITERIO
			     WHERE EV_CG_ID=P_IDCRITERIO;

					 LOGADMINISTRACION_PCK.Insertar(P_US_ID,2,'EVALUACION_CRITERIOSGENERALES',P_IDCRITERIO,'MODIFICAR CRITERIO GENERAL');

	         ELSE

			   NULL;

	         END IF;
		  END IF;
		END IF;
      END IF;
	END IF;


	IF V_ACCION='INSERTARCRITERIO' OR V_ACCION='BORRARCRITERIO' OR V_ACCION='GUARDARCRITERIO' THEN

	  MODIFICARCRITERIOSGENERALES(
        P_US_ID,
        0,
	    NULL,
        NULL,
	    'ANYADIRCRITERIO'
	  );

	ELSE

	  NULL;

	END IF;

  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.MODIFICARCRITERIOSGENERALES',' ',sqlcode,sqlerrm,NULL);


  END;


  /*


  */



  PROCEDURE CREARCRITERIOSACTA(
    P_US_ID              IN NUMBER,
	P_IDACTA             IN NUMBER
  ) IS



	V_IDCRITERIO EVALUACION_CRITERIOSACTAS.EV_CA_ID%TYPE;
	V_IDEMPRESA  EMPRESAS.EMP_ID%TYPE;


	CURSOR cCRITERIOSGENERALES IS
	  SELECT EV_CG_DESCRIPCION DESCRIPCIONCRITERIO,
			 EV_CG_TIPO TIPOCRITERIO
		FROM EVALUACION_CRITERIOSGENERALES
	   WHERE EV_CG_IDEMPRESA=V_IDEMPRESA;


  BEGIN

    V_IDEMPRESA:=Utilidades_PCK.EmpresaDelUsuario(P_US_ID);

	FOR rCRITERIOGENERAL IN cCRITERIOSGENERALES LOOP

	  --SELECT NVL(MAX(EV_CA_ID),0)+1
		--INTO V_IDCRITERIO
		--FROM EVALUACION_CRITERIOSACTAS;

		SELECT EVALUACION_CRITACTAS_SEQ.NEXTVAL
		  INTO V_IDCRITERIO
		  FROM DUAL;


	  INSERT INTO EVALUACION_CRITERIOSACTAS(
	    EV_CA_ID,
		EV_CA_DESCRIPCION,
		EV_CA_TIPO,
	    EV_CA_IDACTA
	  )
	  VALUES(
	    V_IDCRITERIO,
		rCRITERIOGENERAL.DESCRIPCIONCRITERIO,
		rCRITERIOGENERAL.TIPOCRITERIO,
	    P_IDACTA
	  );

	END LOOP;


  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.CREARCRITERIOSACTA',' ',sqlcode,sqlerrm,NULL);


  END;


  /*


  */





  PROCEDURE MODIFICARCRITERIOSACTA(
    P_US_ID              IN NUMBER,
	P_IDACTA             IN NUMBER,
    P_IDCRITERIO         IN NUMBER,
	P_DESCRIPCION        IN VARCHAR2,
    P_TIPOCRITERIO       IN VARCHAR2,
    P_CAMBIOSCRITERIOS   IN VARCHAR2,
	P_ACCION             IN VARCHAR2
  ) IS

    V_ACCION VARCHAR2(100);

	V_IDCRITERIO EVALUACION_CRITERIOSACTAS.EV_CA_ID%TYPE;


	CURSOR cCRITERIO IS
	  SELECT EV_CA_ID IDCRITERIO,
	         EV_CA_DESCRIPCION DESCRIPCIONCRITERIO,
			 EV_CA_TIPO TIPOCRITERIO
		FROM EVALUACION_CRITERIOSACTAS
	   WHERE EV_CA_ID=P_IDCRITERIO;

	CURSOR cPRODUCTOESTANDAR IS
	  SELECT CP_PRO_REFERENCIA REFERENCIA,
	         CP_PRO_NOMBRE NOMBRE,
			 CP_PRO_DESCRIPCION DESCRIPCION
		FROM EVALUACION_ACTAS,
		     CATPRIV_PROVEEDORES,
			 CATPRIV_PRODUCTOSESTANDAR
	   WHERE EV_AC_ID=P_IDACTA
	     AND EV_AC_IDPROVEEDORPRODUCTO=CP_PV_ID
		 AND CP_PV_IDPRODUCTOESTANDAR=CP_PRO_ID;


  BEGIN

    V_ACCION:=NVL(P_ACCION,'ANYADIRCRITERIO');


	IF V_ACCION='ANYADIRCRITERIO' THEN

	  ASIGNARCRITERIOSALACTA(
	    P_CAMBIOSCRITERIOS,
		P_IDACTA
	  );

	  HTP.P(Utilidades_PCK.CabeceraXML);
	  HTP.P('<CRITERIOS>');
	    HTP.P('<PRODUCTOESTANDAR>');
	      FOR rPRODUCTOESTANDAR IN cPRODUCTOESTANDAR LOOP
	        HTP.P('<REFERENCIA>'||rPRODUCTOESTANDAR.REFERENCIA||'</REFERENCIA>');
			HTP.P('<NOMBRE>'||MVM.ScapeHTMLString(rPRODUCTOESTANDAR.NOMBRE)||'</NOMBRE>');
			HTP.P('<DESCRIPCION>'||UTILIDADES_PCK.TEXTOHTML(rPRODUCTOESTANDAR.DESCRIPCION)||'</DESCRIPCION>');
	      END LOOP;
	    HTP.P('</PRODUCTOESTANDAR>');
	  HTP.P('<CRITERIOACTUAL>');
	    HTP.P('<IDACTA>'||P_IDACTA||'</IDACTA>');
		HTP.P('<IDCRITERIO>0</IDCRITERIO>');
	    HTP.P('<DESCRIPCION></DESCRIPCION>');
	    HTP.P('<TIPO>'||P_TIPOCRITERIO||'</TIPO>');
	  HTP.P('</CRITERIOACTUAL>');
	  LISTACRITERIOSACTA(P_IDACTA,'F');
	  LISTACRITERIOSACTA(P_IDACTA,'E');
	  HTP.P('</CRITERIOS>');

	ELSE

	  IF V_ACCION='INSERTARCRITERIO' THEN

		  ASIGNARCRITERIOSALACTA(P_CAMBIOSCRITERIOS,P_IDACTA);

		  --SELECT NVL(MAX(EV_CA_ID),0)+1
		    --INTO V_IDCRITERIO
		    --FROM EVALUACION_CRITERIOSACTAS;


		  SELECT EVALUACION_CRITACTAS_SEQ.NEXTVAL
		    INTO V_IDCRITERIO
		    FROM DUAL;


		  INSERT INTO EVALUACION_CRITERIOSACTAS(
		    EV_CA_ID,
		    EV_CA_DESCRIPCION,
		    EV_CA_TIPO,
			EV_CA_IDACTA
		  )
		  VALUES(
		    V_IDCRITERIO,
		    P_DESCRIPCION,
		    P_TIPOCRITERIO,
			P_IDACTA
		  );



	  ELSE

	    IF V_ACCION='BORRARCRITERIO' THEN


		    DELETE EVALUACION_CRITERIOSACTAS
		     WHERE EV_CA_ID=P_IDCRITERIO;


		ELSE

			IF V_ACCION='MODIFICARCRITERIO' THEN

			    ASIGNARCRITERIOSALACTA(
				   P_CAMBIOSCRITERIOS,
				   P_IDACTA,
				   P_IDCRITERIO
				 );

				HTP.P(Utilidades_PCK.CabeceraXML);
	            HTP.P('<CRITERIOS>');
			      HTP.P('<PRODUCTOESTANDAR>');
	                FOR rPRODUCTOESTANDAR IN cPRODUCTOESTANDAR LOOP
	                  HTP.P('<REFERENCIA>'||rPRODUCTOESTANDAR.REFERENCIA||'</REFERENCIA>');
			          HTP.P('<NOMBRE>'||MVM.ScapeHTMLString(rPRODUCTOESTANDAR.NOMBRE)||'</NOMBRE>');
					  HTP.P('<DESCRIPCION>'||UTILIDADES_PCK.TEXTOHTML(rPRODUCTOESTANDAR.DESCRIPCION)||'</DESCRIPCION>');
	                END LOOP;
	              HTP.P('</PRODUCTOESTANDAR>');
				  FOR rCRITERIO IN cCRITERIO LOOP
	                HTP.P('<CRITERIOACTUAL>');
	                HTP.P('<IDACTA>'||P_IDACTA||'</IDACTA>');
		            HTP.P('<IDCRITERIO>'||rCRITERIO.IDCRITERIO||'</IDCRITERIO>');
	                HTP.P('<DESCRIPCION>'||MVM.ScapeHTMLString(rCRITERIO.DESCRIPCIONCRITERIO)||'</DESCRIPCION>');
	                HTP.P('<TIPO>'||rCRITERIO.TIPOCRITERIO||'</TIPO>');
	                HTP.P('</CRITERIOACTUAL>');
				  END LOOP;
				  LISTACRITERIOSACTA(P_IDACTA,'F',P_IDCRITERIO,-1);
	              LISTACRITERIOSACTA(P_IDACTA,'E',P_IDCRITERIO,-1);
	            HTP.P('</CRITERIOS>');

		  ELSE

			IF V_ACCION='GUARDARCRITERIO' THEN

			    ASIGNARCRITERIOSALACTA(P_CAMBIOSCRITERIOS,P_IDACTA,P_IDCRITERIO);

				UPDATE EVALUACION_CRITERIOSACTAS
			       SET EV_CA_DESCRIPCION=P_DESCRIPCION,
				       EV_CA_TIPO=P_TIPOCRITERIO
			     WHERE EV_CA_ID=P_IDCRITERIO;


	         ELSE

	           IF V_ACCION='ASIGNARCRITERIO' THEN

                ASIGNARCRITERIOSALACTA(
				   P_CAMBIOSCRITERIOS,
				   P_IDACTA
				 );

			   ELSE

			     NULL;

			   END IF;

	         END IF;
		  END IF;
		END IF;
      END IF;
	END IF;


	IF V_ACCION='INSERTARCRITERIO' OR V_ACCION='BORRARCRITERIO' OR V_ACCION='GUARDARCRITERIO' OR V_ACCION='ASIGNARCRITERIO' THEN

	  MODIFICARCRITERIOSACTA(
        P_US_ID,
	    P_IDACTA,
        0,
	    NULL,
        NULL,
        NULL,
	    'ANYADIRCRITERIO'
	  );

	ELSE

	  NULL;

	END IF;

  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.MODIFICARCRITERIOSACTA',' ',sqlcode,sqlerrm,NULL);


  END;


  /*



  */


  PROCEDURE  LISTACRITERIOSGENERALES(
	P_US_ID  IN NUMBER,
	P_TIPO   IN VARCHAR2,
	P_IDCRITERIOEXCLUIDO IN NUMBER DEFAULT -1
  )IS

    V_MARCATIPO_INICIO VARCHAR2(100);
	V_MARCATIPO_FIN VARCHAR2(100);


	V_IDEMPRESA EMPRESAS.EMP_ID%TYPE;

    CURSOR cCRITERIOS IS
	  SELECT EV_CG_ID IDCRITERIO,
		     EV_CG_DESCRIPCION DESCRIPCION,
		     EV_CG_TIPO TIPO
	    FROM EVALUACION_CRITERIOSGENERALES
	   WHERE EV_CG_IDEMPRESA=V_IDEMPRESA
	     AND EV_CG_TIPO=P_TIPO
		 AND EV_CG_ID<>P_IDCRITERIOEXCLUIDO
	   ORDER BY UPPER(EV_CG_DESCRIPCION);

  BEGIN


	V_IDEMPRESA:=Utilidades_PCK.EmpresaDelUsuario(P_US_ID);



    IF P_TIPO='F' THEN

	  V_MARCATIPO_INICIO:='<CRITERIOSFUNCIONALES>';
	  V_MARCATIPO_FIN:='</CRITERIOSFUNCIONALES>';

	ELSE
	  IF P_TIPO='E' THEN
	    V_MARCATIPO_INICIO:='<CRITERIOSENVOLTORIO>';
	    V_MARCATIPO_FIN:='</CRITERIOSENVOLTORIO>';
	  END IF;
	END IF;

	HTP.P(V_MARCATIPO_INICIO);
	  FOR rCRITERIO IN cCRITERIOS LOOP

	    HTP.P('<CRITERIO>');
		  HTP.P('<IDCRITERIO>'||rCRITERIO.IDCRITERIO||'</IDCRITERIO>');
		  HTP.P('<DESCRIPCION>'||MVM.ScapeHTMLString(rCRITERIO.DESCRIPCION)||'</DESCRIPCION>');
		HTP.P('</CRITERIO>');
	  END LOOP;
	HTP.P(V_MARCATIPO_FIN);

	EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.LISTACRITERIOSGENERALES',' ',sqlcode,sqlerrm,NULL);

  END;


  /*



  */

  PROCEDURE  LISTACRITERIOSACTA(
    P_IDACTA IN NUMBER,
	P_TIPO   IN VARCHAR2,
	P_IDCRITERIOEXCLUIDO IN NUMBER DEFAULT -1,
	P_IDINFORME IN NUMBER DEFAULT -1
  )IS

    V_MARCATIPO_INICIO VARCHAR2(100);
	V_MARCATIPO_FIN VARCHAR2(100);

	V_IDEMPRESA EMPRESAS.EMP_ID%TYPE;


	-- CURSOR CON LOS CRITERIOS

    CURSOR cCRITERIOS IS
	  SELECT EV_CA_ID IDCRITERIO,
	         EV_CA_DESCRIPCION DESCRIPCION
	    FROM EVALUACION_CRITERIOSACTAS
       WHERE EV_CA_IDACTA=P_IDACTA
		 AND EV_CA_TIPO=P_TIPO
		 AND EV_CA_ID<>P_IDCRITERIOEXCLUIDO
	ORDER BY UPPER(EV_CA_DESCRIPCION);


	-- CURSOR CON LOS CRITERIOS Y LAS RESPUESTAS DE UN INFORME DADO

	CURSOR cCRITERIOSCONRESPUESTA IS
	  SELECT EV_CA_ID IDCRITERIO,
	         EV_CA_DESCRIPCION DESCRIPCION,
			 EV_RC_ID  IDRESPUESTA,
			 DECODE(EV_RC_APTO,NULL,'P',EV_RC_APTO) APTO,
			 EV_RC_COMENTARIOS COMENTARIOS
	    FROM EVALUACION_CRITERIOSACTAS,
		     EVALUACION_RESPUESTASCRITERIOS
       WHERE EV_CA_IDACTA=P_IDACTA
		 AND EV_CA_TIPO=P_TIPO
		 AND EV_CA_ID=EV_RC_IDCRITERIOACTA(+)
		 AND P_IDINFORME=EV_RC_IDINFORME(+)
	ORDER BY UPPER(EV_CA_DESCRIPCION);



  BEGIN



    IF P_TIPO='F' THEN

	  V_MARCATIPO_INICIO:='<CRITERIOSFUNCIONALES>';
	  V_MARCATIPO_FIN:='</CRITERIOSFUNCIONALES>';

	ELSE
	  IF P_TIPO='E' THEN

	    V_MARCATIPO_INICIO:='<CRITERIOSENVOLTORIO>';
	    V_MARCATIPO_FIN:='</CRITERIOSENVOLTORIO>';

	  END IF;
	END IF;



	HTP.P(V_MARCATIPO_INICIO);
	  IF P_IDINFORME=-1 THEN
	    FOR rCRITERIO IN cCRITERIOS LOOP
	      HTP.P('<CRITERIO>');
		    HTP.P('<IDCRITERIO>'||rCRITERIO.IDCRITERIO||'</IDCRITERIO>');
		    HTP.P('<DESCRIPCION>'||MVM.ScapeHTMLString(rCRITERIO.DESCRIPCION)||'</DESCRIPCION>');
		  HTP.P('</CRITERIO>');
	    END LOOP;
	  ELSE

	    FOR rCRITERIO IN cCRITERIOSCONRESPUESTA LOOP
	      HTP.P('<CRITERIO>');
		    HTP.P('<IDCRITERIO>'||rCRITERIO.IDCRITERIO||'</IDCRITERIO>');
		    HTP.P('<DESCRIPCION>'||MVM.ScapeHTMLString(rCRITERIO.DESCRIPCION)||'</DESCRIPCION>');
			HTP.P('<APTO>'||rCRITERIO.APTO||'</APTO>');
			HTP.P('<COMENTARIOS>'||MVM.ScapeHTMLString(rCRITERIO.COMENTARIOS)||'</COMENTARIOS>');
			HTP.P('<COMENTARIOS_HTML>'||Utilidades_pck.TEXTOHTML(rCRITERIO.COMENTARIOS)||'</COMENTARIOS_HTML>');
		  HTP.P('</CRITERIO>');
	    END LOOP;



	  END IF;
	HTP.P(V_MARCATIPO_FIN);


	EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.LISTACRITERIOSACTA'||P_IDACTA||' '||P_TIPO||' '||P_IDINFORME,' ',sqlcode,sqlerrm,NULL);

  END;


    /*



  */


  PROCEDURE  LISTACRITERIOSINFORME(
	P_IDINFORME IN NUMBER,
	P_TIPO   IN VARCHAR2
  )IS

    V_IDACTA EVALUACION_ACTAS.EV_AC_ID%TYPE;




  BEGIN

     SELECT EV_IN_IDACTA
	   INTO V_IDACTA
	   FROM EVALUACION_INFORMES
	  WHERE EV_IN_ID=P_IDINFORME;

	  LISTACRITERIOSACTA(
	    V_IDACTA,
		P_TIPO,
		-1,
		P_IDINFORME
      );

	EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.LISTACRITERIOSINFORME',' ',sqlcode,sqlerrm,NULL);

  END;


  /*



  */





  PROCEDURE ASIGNARCRITERIOSALACTA(
    P_CAMBIOSCRITERIOS IN VARCHAR2,
	P_IDACTA           IN NUMBER,
	P_IDCRITERIO	   IN NUMBER DEFAULT -1
  )
  IS

    V_CADENA VARCHAR2(3000);

	V_IDACTA         NUMBER;
	V_IDCRITERIO      VARCHAR2(3000);
	V_BORRAR     VARCHAR2(500);

	V_IDCRITERIOACTA EVALUACION_CRITERIOSACTAS.EV_CA_ID%TYPE;

	V_EV_CG_IDEMPRESA EVALUACION_CRITERIOSGENERALES.EV_CG_IDEMPRESA%TYPE;
	V_CG_DESCRIPCION  EVALUACION_CRITERIOSGENERALES.EV_CG_DESCRIPCION%TYPE;
	V_CG_TIPO         EVALUACION_CRITERIOSGENERALES.EV_CG_TIPO%TYPE;

  BEGIN

    IF	P_CAMBIOSCRITERIOS IS NOT NULL THEN




		FOR I IN 0..Utilidades_PCK.PieceCount(P_CAMBIOSCRITERIOS,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_CAMBIOSCRITERIOS,'#',I);

			V_IDACTA      :=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			V_IDCRITERIO  :=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',1));
			V_BORRAR     :=    Utilidades_PCK.Piece(V_CADENA,'|',2);


			IF V_BORRAR='S' AND P_IDCRITERIO<>V_IDCRITERIO THEN


			 DELETE EVALUACION_CRITERIOSACTAS
			 WHERE EV_CA_ID=V_IDCRITERIO;

			END IF;

		END LOOP;

	END IF;

	EXCEPTION


	    WHEN OTHERS THEN

		 MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.ASIGNARCRITERIOSALACTA',' ',sqlcode,sqlerrm,NULL);

  END;


  PROCEDURE BORRARCRITERIOSACTAS(
    P_IDACTA IN NUMBER
  )
  IS

    CURSOR cCRITERIOSACTAS IS
	  SELECT EV_CA_ID IDCRITERIOACTA
	    FROM EVALUACION_CRITERIOSACTAS
	   WHERE EV_CA_IDACTA=P_IDACTA;

  BEGIN

    FOR rCRITERIOACTA IN cCRITERIOSACTAS LOOP

	  BORRARRESPUESTASCRITERIOS(rCRITERIOACTA.IDCRITERIOACTA);

	END LOOP;

	DELETE EVALUACION_CRITERIOSACTAS
	   WHERE EV_CA_IDACTA=P_IDACTA;


  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.BORRARCRITERIOSACTAS',' ',sqlcode,sqlerrm,NULL);

  END;


  /*


  */

  PROCEDURE BORRARRESPUESTASCRITERIOS(
    P_IDCRITERIOACTA IN NUMBER
  )
  IS

  BEGIN

	DELETE EVALUACION_RESPUESTASCRITERIOS
	   WHERE EV_RC_IDCRITERIOACTA=P_IDCRITERIOACTA;


  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.BORRARRESPUESTASCRITERIOS',' ',sqlcode,sqlerrm,NULL);

  END;

  FUNCTION CRITERIOSMODIFICABLES(
    P_IDACTA IN NUMBER
  )  RETURN BOOLEAN
  IS

    -- CURSOR CON TODOS LOS INFORMES DEL ACTA

	 CURSOR cINFORMES IS
       SELECT EV_IN_ID
	     FROM EVALUACION_INFORMES
		WHERE EV_IN_IDACTA=P_IDACTA;

	 V_MODIFICABLE BOOLEAN;

  BEGIN

    V_MODIFICABLE:=TRUE;


    FOR rINFORME IN cINFORMES LOOP
	  IF OBTENERESTADOINFORME(rINFORME.EV_IN_ID)>10 THEN
	    V_MODIFICABLE:=FALSE;
	  END IF;
	END LOOP;





	RETURN V_MODIFICABLE;


	EXCEPTION
    WHEN OTHERS THEN

	  RETURN FALSE;
	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.CRITERIOSMODIFICABLES',' ',sqlcode,sqlerrm,NULL);

  END;



  PROCEDURE GUARDARRESPUESTASCRITERIOS(
    P_IDINFORME IN NUMBER,
	P_CAMBIOSCRITERIOS IN VARCHAR2
  ) IS


    V_CADENA VARCHAR2(3000);

	V_IDCRITERIOACTA EVALUACION_RESPUESTASCRITERIOS.EV_RC_IDCRITERIOACTA%TYPE;

	V_IDCRITERIO EVALUACION_RESPUESTASCRITERIOS.EV_RC_ID%TYPE;

	V_APTO EVALUACION_RESPUESTASCRITERIOS.EV_RC_APTO%TYPE;

	V_COMENTARIO EVALUACION_RESPUESTASCRITERIOS.EV_RC_COMENTARIOS%TYPE;


  BEGIN

    IF P_CAMBIOSCRITERIOS IS NOT NULL THEN

	  DELETE EVALUACION_RESPUESTASCRITERIOS
	   WHERE EV_RC_IDINFORME=P_IDINFORME;

		FOR I IN 0..Utilidades_PCK.PieceCount(P_CAMBIOSCRITERIOS,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_CAMBIOSCRITERIOS,'#',I);

			V_IDCRITERIOACTA :=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			V_COMENTARIO     :=	Utilidades_PCK.Piece(V_CADENA,'|',1);
			V_APTO           := Utilidades_PCK.Piece(V_CADENA,'|',2);

    --SELECT NVL(MAX(EV_RC_ID),0)+1
		  --INTO V_IDCRITERIO
		  --FROM EVALUACION_RESPUESTASCRITERIOS;

			SELECT EVALUACION_RESPCRIT_SEQ.NEXTVAL
		    INTO V_IDCRITERIO
		    FROM DUAL;



		INSERT INTO EVALUACION_RESPUESTASCRITERIOS(
		  EV_RC_ID,
		  EV_RC_IDINFORME,
		  EV_RC_IDCRITERIOACTA,
		  EV_RC_COMENTARIOS,
		  EV_RC_APTO
		)
		VALUES(
		  V_IDCRITERIO,
		  P_IDINFORME,
		  V_IDCRITERIOACTA,
		  V_COMENTARIO,
		  V_APTO
		);


		END LOOP;

	END IF;




  EXCEPTION
    WHEN OTHERS THEN

	   MVM.InsertDBError (' EVALUACIONPRODUCTOS_PCK.GUARDARRESPUESTASCRITERIOS',' ',sqlcode,sqlerrm,NULL);


  END;


  PROCEDURE BORRARRESPUESTASINFORME(
    P_IDINFORME IN NUMBER
  )
  IS

  BEGIN

	DELETE EVALUACION_RESPUESTASCRITERIOS
	   WHERE EV_RC_IDINFORME=P_IDINFORME;


  EXCEPTION

    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.BORRARRESPUESTASINFORME',' ',sqlcode,sqlerrm,NULL);

  END;






  PROCEDURE ADJUDICARPRODUCTOS(
    P_US_ID IN NUMBER,
	P_CAMBIOSADJUDICATURAS IN VARCHAR2
  )
  IS

    V_CADENA VARCHAR2(10);

	V_IDPROVEEDOR        CATPRIV_PROVEEDORES.CP_PV_ID%TYPE;
	V_ADJUDICAR          CATPRIV_PROVEEDORES.CP_PV_ADJUDICADO%TYPE;
	V_APTOPORHIST          CATPRIV_PROVEEDORES.CP_PV_APTOHISTORICO%TYPE;

	V_ADJUDICAR_ANTERIOR          CATPRIV_PROVEEDORES.CP_PV_ADJUDICADO%TYPE;
	V_APTOPORHIST_ANTERIOR        CATPRIV_PROVEEDORES.CP_PV_APTOHISTORICO%TYPE;

	-- PROVEEDOR DEL CP
	CURSOR cPRODUCTOS_EN_PLANTILLAS(IDPROVEEDOR NUMBER) IS
      SELECT CP_PV_IDPRODUCTO,
	         PL_ID
        FROM CATPRIV_PROVEEDORES,
             PLANTILLAS,
	         LINEASPLANTILLAS,
	         PRODUCTOSLINEASPLANTILLAS
       WHERE CP_PV_ID=IDPROVEEDOR
         AND LIP_IDPLANTILLA=PL_ID
         AND PL_IDEMPRESA=CP_PV_IDEMPRESA
         AND PLP_IDLINEAPLANTILLA=LIP_ID
         AND PLP_IDPRODUCTO=CP_PV_IDPRODUCTO;

  BEGIN

    IF P_CAMBIOSADJUDICATURAS IS NOT NULL THEN

		FOR I IN 0..Utilidades_PCK.PieceCount(P_CAMBIOSADJUDICATURAS,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_CAMBIOSADJUDICATURAS,'#',I);

			V_IDPROVEEDOR      :=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			V_ADJUDICAR      :=    Utilidades_PCK.Piece(V_CADENA,'|',1);
			V_APTOPORHIST    :=   Utilidades_PCK.Piece(V_CADENA,'|',2);


			-- GUARDAMOS EL ESTADO ANTERIOR
			SELECT CP_PV_ADJUDICADO,
			       CP_PV_APTOHISTORICO
				INTO V_ADJUDICAR_ANTERIOR,
	           V_APTOPORHIST_ANTERIOR
			  FROM CATPRIV_PROVEEDORES
			 WHERE CP_PV_ID=V_IDPROVEEDOR;

			UPDATE CATPRIV_PROVEEDORES
			   SET CP_PV_ADJUDICADO=V_ADJUDICAR,
				     CP_PV_APTOHISTORICO=V_APTOPORHIST
			 WHERE CP_PV_ID=V_IDPROVEEDOR;


			 -- SI ES HA MODIFICADO LA ADJUDICACION GUARDAMOS LA FECHA Y EL USUARIO

			 IF NVL(V_ADJUDICAR_ANTERIOR,'N')<>NVL(V_ADJUDICAR,'N') THEN

				 UPDATE CATPRIV_PROVEEDORES
			      SET CP_PV_FECHAADJUDICACION=TO_DATE(SYSDATE),
				        CP_PV_IDUSUARIOADJUDICACION=P_US_ID
			    WHERE CP_PV_ID=V_IDPROVEEDOR;

				-- HEMOS DESADJUDICADO UN PRODUCTO,
				-- LO ELIMINAMOS DE LAS PLANTILLAS
				IF V_ADJUDICAR='N' THEN

				  FOR rPRODUCTO IN cPRODUCTOS_EN_PLANTILLAS(V_IDPROVEEDOR) LOOP
				    MVM_V3_PCK.BorrarProductoDePlantilla(P_US_ID,rPRODUCTO.PL_ID,rPRODUCTO.CP_PV_IDPRODUCTO);
				  END LOOP;

				END IF;


					LOGADMINISTRACION_PCK.Insertar(P_US_ID,2,'CATPRIV_PROVEEDORES',V_IDPROVEEDOR,'MODIFICADA LA ADJUDICACION');

			 END IF;

			 -- SI ES HA MODIFICADO EL APTO POR HISTORICO GUARDAMOS LA FECHA Y EL USUARIO

			 IF NVL(V_APTOPORHIST_ANTERIOR,'N')<>NVL(V_APTOPORHIST,'N') THEN

				 UPDATE CATPRIV_PROVEEDORES
			      SET CP_PV_FECHAAPTOHISTORICO=TO_DATE(SYSDATE),
				        CP_PV_IDUSUARIOAPTOHISTORICO=P_US_ID
			    WHERE CP_PV_ID=V_IDPROVEEDOR;

					LOGADMINISTRACION_PCK.Insertar(P_US_ID,2,'CATPRIV_PROVEEDORES',V_IDPROVEEDOR,'MODIFICADA EL APTO POR HISTORICO');

			 END IF;




		END LOOP;

	END IF;

	EXCEPTION


	    WHEN OTHERS THEN

		 MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.ADJUDICARPRODUCTOS',' ',sqlcode,sqlerrm,NULL);

  END;



  -- desadjudicamos proveedores desde el listado completo

  PROCEDURE DESADJUDICARPROVEEDORES(
    P_US_ID IN NUMBER,
	P_CAMBIOSADJUDICATURAS IN VARCHAR2
  )
  IS

    V_CADENA VARCHAR2(10);

	V_IDPROVEEDOR        CATPRIV_PROVEEDORES.CP_PV_ID%TYPE;
	V_ADJUDICAR          CATPRIV_PROVEEDORES.CP_PV_ADJUDICADO%TYPE;

	V_ADJUDICAR_ANTERIOR          CATPRIV_PROVEEDORES.CP_PV_ADJUDICADO%TYPE;

	-- PROVEEDOR DEL CP
	CURSOR cPRODUCTOS_EN_PLANTILLAS(IDPROVEEDOR NUMBER) IS
      SELECT CP_PV_IDPRODUCTO,
	         PL_ID
        FROM CATPRIV_PROVEEDORES,
             PLANTILLAS,
	         LINEASPLANTILLAS,
	         PRODUCTOSLINEASPLANTILLAS
       WHERE CP_PV_ID=IDPROVEEDOR
         AND LIP_IDPLANTILLA=PL_ID
         AND PL_IDEMPRESA=CP_PV_IDEMPRESA
         AND PLP_IDLINEAPLANTILLA=LIP_ID
         AND PLP_IDPRODUCTO=CP_PV_IDPRODUCTO;

  BEGIN

    IF P_CAMBIOSADJUDICATURAS IS NOT NULL THEN

		FOR I IN 0..Utilidades_PCK.PieceCount(P_CAMBIOSADJUDICATURAS,'#')-2 LOOP


			V_CADENA:=Utilidades_PCK.Piece(P_CAMBIOSADJUDICATURAS,'#',I);

			V_IDPROVEEDOR      :=	TO_NUMBER(Utilidades_PCK.Piece(V_CADENA,'|',0));
			V_ADJUDICAR      :=    Utilidades_PCK.Piece(V_CADENA,'|',1);


			-- GUARDAMOS EL ESTADO ANTERIOR
			SELECT CP_PV_ADJUDICADO
				INTO V_ADJUDICAR_ANTERIOR
			  FROM CATPRIV_PROVEEDORES
			 WHERE CP_PV_ID=V_IDPROVEEDOR;

			UPDATE CATPRIV_PROVEEDORES
			   SET CP_PV_ADJUDICADO=V_ADJUDICAR
			 WHERE CP_PV_ID=V_IDPROVEEDOR;


			 -- SI ES HA MODIFICADO LA ADJUDICACION GUARDAMOS LA FECHA Y EL USUARIO

			 IF NVL(V_ADJUDICAR_ANTERIOR,'N')<>NVL(V_ADJUDICAR,'N') THEN

				 UPDATE CATPRIV_PROVEEDORES
			      SET CP_PV_FECHAADJUDICACION=TO_DATE(SYSDATE),
				        CP_PV_IDUSUARIOADJUDICACION=P_US_ID
			    WHERE CP_PV_ID=V_IDPROVEEDOR;

				-- HEMOS DESADJUDICADO UN PRODUCTO,
				-- LO ELIMINAMOS DE LAS PLANTILLAS
				IF V_ADJUDICAR='N' THEN

				  FOR rPRODUCTO IN cPRODUCTOS_EN_PLANTILLAS(V_IDPROVEEDOR) LOOP
				    MVM_V3_PCK.BorrarProductoDePlantilla(P_US_ID,rPRODUCTO.PL_ID,rPRODUCTO.CP_PV_IDPRODUCTO);
				  END LOOP;

				END IF;

					LOGADMINISTRACION_PCK.Insertar(P_US_ID,2,'CATPRIV_PROVEEDORES',V_IDPROVEEDOR,'MODIFICADA LA ADJUDICACION(DESDE EL LISTADO)');

			 END IF;

		END LOOP;

	END IF;

	  HTP.P('<OK/>');

	EXCEPTION


	    WHEN OTHERS THEN
		 MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.DESADJUDICARPROVEEDORES',' ',sqlcode,sqlerrm,NULL);
		 HTP.P('<ERROR/>');

  END;


  PROCEDURE ADJUDICATURAPROVEEDOR(
    P_IDPROVEEDOR IN NUMBER
  )
  IS

    V_IDACTA EVALUACION_ACTAS.EV_AC_ID%TYPE;
	V_APTO   EVALUACION_ACTAS.EV_AC_APTO%TYPE;
	V_ADJUDICADO CATPRIV_PROVEEDORES.CP_PV_ADJUDICADO%TYPE;
	V_STATUS EVALUACION_ACTAS.EV_AC_STATUS%TYPE;


  BEGIN

    SELECT EV_AC_ID,
	       NVL(EV_AC_APTO,'P'),
		   EV_AC_STATUS
	  INTO V_IDACTA,
	       V_APTO,
		   V_STATUS
	  FROM EVALUACION_ACTAS
	 WHERE EV_AC_IDPROVEEDORPRODUCTO=P_IDPROVEEDOR;

   IF V_APTO='S' THEN
     SELECT NVL(CP_PV_ADJUDICADO,'N')
	   INTO V_ADJUDICADO
	   FROM CATPRIV_PROVEEDORES
	  WHERE CP_PV_ID=P_IDPROVEEDOR;
   END IF;

   HTP.P('<EVALUACION>');
     HTP.P('<APTO>'||V_APTO||'</APTO>');
	 HTP.P('<STATUS>'||V_STATUS||'</STATUS>');
	 HTP.P('<ADJUDICADO>'||V_ADJUDICADO||'</ADJUDICADO>');
   HTP.P('</EVALUACION>');

  EXCEPTION
     WHEN NO_DATA_FOUND THEN


		 -- no hay datos del acta miramos si es apto por historico y si esta adjudicado
		   SELECT NVL(CP_PV_APTOHISTORICO,'N'),
			        NVL(CP_PV_ADJUDICADO,'N')
				 INTO	V_APTO,
	            V_ADJUDICADO
	       FROM CATPRIV_PROVEEDORES
	      WHERE CP_PV_ID=P_IDPROVEEDOR;


		 -- MANTENEMOS LA COMPATIBILIDAD CON LO QUE YA HAY,
		 -- SI ESTA ADJUDICADO LO DAMOS COMO APTO POR HISTORICO
		 IF V_ADJUDICADO='S' THEN
		   V_APTO:='S';
		 END IF;


		 -- SI ES APTO DEVOLVEMOS OS DATOS
		 IF V_APTO='S' THEN

		   HTP.P('<EVALUACION>');
         HTP.P('<APTO>'||V_APTO||'</APTO>');
		   HTP.P('<STATUS></STATUS>');
	       HTP.P('<ADJUDICADO>'||V_ADJUDICADO||'</ADJUDICADO>');
       HTP.P('</EVALUACION>');

		 -- NO HAY DATOS
		 ELSE

		   HTP.P('<EVALUACION>');
             HTP.P('<NO_INICIADA/>');
		     HTP.P('<STATUS></STATUS>');
           HTP.P('</EVALUACION>');

		 END IF;

    WHEN OTHERS THEN

      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.ADJUDICATURAPROVEEDOR',' ',sqlcode,sqlerrm,NULL);

  END;

  FUNCTION OBTENER_ETIQUETA_ESTADO_UNIV(
    P_IDESTADO NUMBER,
	P_IDTIPOESTADO NUMBER
  )RETURN VARCHAR2
  IS

    V_ETIQUETA estados_universales.EST_UNI_NOMBRE%TYPE;

  BEGIN

    SELECT EST_UNI_NOMBRE
	  into V_ETIQUETA
	  FROM estados_universales,
	       estados_universales_tipos,
		   estados_universales_agrupados
	 where est_uni_tp_id=est_uni_idtipo
	   and est_uni_id=est_uni_agr_idestado_univ
	   and est_uni_agr_idtipoestado_univ=est_uni_idtipo
	   and est_uni_agr_id=P_IDESTADO
	   and est_uni_agr_idtipoestado_univ=P_IDTIPOESTADO;


  return V_ETIQUETA;



  EXCEPTION
    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.OBTENER_ETIQUETA_ESTADO_UNIV',' P_IDTIPOESTADO: '||P_IDTIPOESTADO||' P_IDESTADO: '||P_IDESTADO,sqlcode,sqlerrm,NULL);
	  RETURN 'Sin estado';

  END;

  FUNCTION OBTENER_IDESTADO_UNIV(
    P_IDESTADO NUMBER,
	P_IDTIPOESTADO NUMBER
  )RETURN number
  IS

    V_idestado estados_universales.EST_UNI_ID%TYPE;

  BEGIN

    SELECT EST_UNI_ID
	  into V_idestado
	  FROM estados_universales,
	       estados_universales_tipos,
		   estados_universales_agrupados
	 where est_uni_tp_id=est_uni_idtipo
	   and est_uni_id=est_uni_agr_idestado_univ
	   and est_uni_agr_idtipoestado_univ=est_uni_idtipo
	   and est_uni_agr_id=P_IDESTADO
	   and est_uni_agr_idtipoestado_univ=P_IDTIPOESTADO;


  return V_idestado;



  EXCEPTION
    WHEN OTHERS THEN
      MVM.InsertDBError ('EVALUACIONPRODUCTOS_PCK.OBTENER_IDESTADO_UNIV',' P_IDTIPOESTADO: '||P_IDTIPOESTADO||' P_IDESTADO: '||P_IDESTADO,sqlcode,sqlerrm,NULL);
	  RETURN -1;

  END;


END;



/
SHOW ERRORS;
EXIT;
